package tui

import (
	"bufio"
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The golden file is generated by running the upstream
// CombinedAutocompleteProvider against a fixture tree (tui/testdata/
// autocomplete_corpus.json). The tree is recreated per test run; the absolute
// paths in the golden are normalized to the temporary directory.

const autocompleteFixtureFiles = "alpha.txt,beta.md,gamma/one.txt,gamma/two.txt,gamma/deep/three.txt,delta/,src/main.ts,src/lib/util.go,src/lib/helper.go,docs/guide.md,.git/ignored.txt,with space.txt,UPPER.TXT,zeta.txt"

func buildAutocompleteFixture(t *testing.T, root string) {
	t.Helper()
	for _, entry := range strings.Split(autocompleteFixtureFiles, ",") {
		isDir := strings.HasSuffix(entry, "/")
		full := filepath.Join(root, filepath.FromSlash(strings.TrimSuffix(entry, "/")))
		if isDir {
			if err := os.MkdirAll(full, 0o755); err != nil {
				t.Fatalf("mkdir %s: %v", full, err)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", filepath.Dir(full), err)
		}
		if err := os.WriteFile(full, []byte("x"), 0o644); err != nil {
			t.Fatalf("write %s: %v", full, err)
		}
	}
}

type autocompleteSpec struct {
	Lines      []string `json:"lines"`
	CursorLine *int     `json:"cursorLine"`
	CursorCol  *int     `json:"cursorCol"`
	Force      bool     `json:"force"`
	FD         *bool    `json:"fd"`
	Apply      *int     `json:"apply"`
}

func autocompleteTestCommands() []CommandEntry {
	return []CommandEntry{
		{Name: "help", Description: "Show help"},
		{Name: "model", Description: "Select model", ArgumentHint: "<name>",
			GetArgumentCompletions: func(prefix string) ([]AutocompleteItem, bool) {
				all := []string{"gpt-4", "gpt-4o", "claude-3"}
				var filtered []AutocompleteItem
				for _, model := range all {
					if strings.HasPrefix(model, prefix) {
						filtered = append(filtered, AutocompleteItem{Value: model, Label: model})
					}
				}
				if len(filtered) == 0 {
					return nil, false
				}
				return filtered, true
			}},
		{Name: "skill:foo", Description: "A skill"},
		{Name: "plain", Label: "plain", Description: "plain entry"},
	}
}

// TestFileCompletionUnderHomeFiltersInsideHome covers `~/.` + Tab. The last
// segment has to be filtered inside the home directory: expanding the prefix
// first ate the "." (filepath.Join cleans the path), which left Dir/Base looking
// at home's *parent* — so `~/.` listed /home and offered `~/dat/`.
func TestFileCompletionUnderHomeFiltersInsideHome(t *testing.T) {
	home := t.TempDir()
	for _, name := range []string{".bashrc", ".config", "dat", "notes.txt"} {
		full := filepath.Join(home, name)
		if name == ".config" || name == "dat" {
			if err := os.MkdirAll(full, 0o755); err != nil {
				t.Fatal(err)
			}
			continue
		}
		if err := os.WriteFile(full, []byte("x"), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	t.Setenv("HOME", home)
	// os.UserHomeDir reads USERPROFILE on Windows; pinning only HOME left this
	// test completing against the developer's real home directory there.
	t.Setenv("USERPROFILE", home)

	provider := NewCombinedAutocompleteProvider(nil, home, "")
	suggestions := provider.GetSuggestions(context.Background(), []string{"~/."}, 0, len("~/."), true)
	if suggestions == nil {
		t.Fatal("no suggestions for ~/.")
	}
	var got []string
	for _, item := range suggestions.Items {
		got = append(got, item.Value)
	}
	if strings.Join(got, " ") != "~/.config/ ~/.bashrc" {
		t.Fatalf("~/.	 suggested %q; want the home directory's dotfiles", got)
	}
	if suggestions.Prefix != "~/." {
		t.Fatalf("prefix = %q", suggestions.Prefix)
	}

	// A trailing ".." names a directory too, and unlike "." it is not a name
	// prefix: the filter is empty and the ".." has to stay in the suggestion —
	// dropping it would point at `~/<name>`, which is home, not home's parent.
	parent := filepath.Dir(home)
	parentSuggestions := provider.GetSuggestions(context.Background(), []string{"~/.."}, 0, len("~/.."), true)
	if parentSuggestions == nil {
		t.Fatal("no suggestions for ~/..")
	}
	got = got[:0]
	for _, item := range parentSuggestions.Items {
		got = append(got, item.Value)
		if !strings.HasPrefix(item.Value, "~/../") {
			t.Fatalf("~/..\t suggested %q; the parent has to stay in the path", item.Value)
		}
		entry := strings.TrimSuffix(strings.TrimPrefix(item.Value, "~/../"), "/")
		if _, err := os.Stat(filepath.Join(parent, entry)); err != nil {
			t.Fatalf("~/..\t suggested %q, which does not exist in the parent", item.Value)
		}
	}
	if want := "~/../" + filepath.Base(home) + "/"; strings.Join(got, " ") != want {
		t.Fatalf("~/..\t suggested %q; want %q", got, want)
	}
}

// TestAutocompleteAgainstUpstreamGolden replays the upstream provider corpus.
func TestAutocompleteAgainstUpstreamGolden(t *testing.T) {
	fdPath, err := exec.LookPath("fd")
	if err != nil {
		t.Skip("fd is not installed")
	}

	goldenFile, err := os.Open("testdata/autocomplete_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	golden := map[string]string{}
	scanner := bufio.NewScanner(goldenFile)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		golden[strings.TrimPrefix(parts[0], "ac ")] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	goldenFile.Close()

	data, err := os.ReadFile("testdata/autocomplete_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := map[string]autocompleteSpec{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	root := t.TempDir()
	buildAutocompleteFixture(t, root)
	fixturePath := "/tmp/keysmatrix/acfix"

	labels := make([]string, 0, len(corpus))
	for label := range corpus {
		labels = append(labels, label)
	}
	sortStrings(labels)

	for _, label := range labels {
		spec := corpus[label]
		useFD := true
		if spec.FD != nil {
			useFD = *spec.FD
		}
		fd := fdPath
		if !useFD {
			fd = ""
		}
		provider := NewCombinedAutocompleteProvider(autocompleteTestCommands(), root, fd)

		lines := append([]string(nil), spec.Lines...)
		cursorLine := 0
		if spec.CursorLine != nil {
			cursorLine = *spec.CursorLine
		}
		cursorCol := 0
		if len(lines) > 0 {
			cursorCol = len(lines[0])
		}
		if spec.CursorCol != nil {
			cursorCol = *spec.CursorCol
		}
		cursorCol = jsOffsetToByteOffset(lines[cursorLine], cursorCol)

		suggestions := provider.GetSuggestions(context.Background(), lines, cursorLine, cursorCol, spec.Force)
		var normalized any
		if suggestions != nil {
			items := make([]map[string]any, 0, len(suggestions.Items))
			for _, item := range suggestions.Items {
				entry := map[string]any{"value": item.Value, "label": item.Label}
				if item.Description != "" {
					entry["description"] = item.Description
				}
				items = append(items, entry)
			}
			normalized = map[string]any{"prefix": suggestions.Prefix, "items": items}
		}
		checkAutocompleteGolden(t, golden, label+" suggestions", normalized, fixturePath, root)

		if spec.Apply != nil && suggestions != nil && *spec.Apply < len(suggestions.Items) {
			result := provider.ApplyCompletion(lines, cursorLine, cursorCol, suggestions.Items[*spec.Apply], suggestions.Prefix)
			applied := map[string]any{
				"lines":      result.Lines,
				"cursorLine": result.CursorLine,
				"cursorCol":  result.CursorCol,
			}
			checkAutocompleteGolden(t, golden, label+" apply", applied, fixturePath, root)
		}

		trigger := provider.ShouldTriggerFileCompletion(lines, cursorLine, cursorCol)
		checkAutocompleteGolden(t, golden, label+" trigger", trigger, fixturePath, root)
	}
}

// stableJSONValue parses and re-serializes a value (or a JSON string) with
// sorted object keys.
func stableJSONValue(t *testing.T, value any) string {
	t.Helper()
	var encoded string
	if text, ok := value.(string); ok {
		encoded = text
	} else {
		encoded = mustJSON(value)
	}
	var parsed any
	if err := json.Unmarshal([]byte(encoded), &parsed); err != nil {
		t.Fatalf("bad JSON %q: %v", encoded, err)
	}
	return stableMDValue(parsed)
}

func checkAutocompleteGolden(t *testing.T, golden map[string]string, label string, got any, fixturePath string, root string) {
	t.Helper()
	want, ok := golden[label]
	if !ok {
		t.Fatalf("missing golden %q", label)
	}
	// Both sides are re-serialized with sorted keys: JSON.stringify preserves
	// the upstream object literal order, Go maps do not.
	rendered := strings.ReplaceAll(stableJSONValue(t, got), fixturePath, root)
	wantStable := strings.ReplaceAll(stableJSONValue(t, want), fixturePath, root)
	if rendered != wantStable {
		t.Fatalf("%s:\n got %s\nwant %s", label, rendered, wantStable)
	}
}

// TestAutocompleteHelpers covers the pure helpers of the provider.
func TestAutocompleteHelpers(t *testing.T) {
	if got := buildFdPathQuery("src/lib"); got != `src[\\/]lib` {
		t.Fatalf("buildFdPathQuery = %q", got)
	}
	if got := buildFdPathQuery("src/"); got != `src[\\/]` {
		t.Fatalf("buildFdPathQuery trailing = %q", got)
	}
	if got := buildFdPathQuery("plain"); got != "plain" {
		t.Fatalf("buildFdPathQuery plain = %q", got)
	}
	if got := buildFdPathQuery("a.b/c+d"); got != `a\.b[\\/]c\+d` {
		t.Fatalf("buildFdPathQuery escaped = %q", got)
	}

	parsed := parsePathPrefix(`@"a b`)
	if !parsed.isAtPrefix || !parsed.isQuotedPrefix || parsed.rawPrefix != "a b" {
		t.Fatalf("parsed = %+v", parsed)
	}
	parsed = parsePathPrefix(`"a`)
	if parsed.isAtPrefix || !parsed.isQuotedPrefix || parsed.rawPrefix != "a" {
		t.Fatalf("parsed = %+v", parsed)
	}
	parsed = parsePathPrefix("@a")
	if !parsed.isAtPrefix || parsed.isQuotedPrefix || parsed.rawPrefix != "a" {
		t.Fatalf("parsed = %+v", parsed)
	}

	if got := buildCompletionValue("with space.txt", false, true, false); got != `@"with space.txt"` {
		t.Fatalf("buildCompletionValue = %q", got)
	}
	if got := buildCompletionValue("plain.txt", false, true, false); got != "@plain.txt" {
		t.Fatalf("buildCompletionValue = %q", got)
	}

	if got := findLastDelimiter("a b/c"); got != 1 {
		t.Fatalf("findLastDelimiter = %d", got)
	}
	if _, ok := findUnclosedQuoteStart(`abc`); ok {
		t.Fatal("unexpected unclosed quote")
	}
	if index, ok := findUnclosedQuoteStart(`a "b`); !ok || index != 2 {
		t.Fatalf("findUnclosedQuoteStart = %d,%v", index, ok)
	}
	if value, ok := extractQuotedPrefix(`hello @"wor`); !ok || value != `@"wor` {
		t.Fatalf("extractQuotedPrefix = %q,%v", value, ok)
	}

	provider := NewCombinedAutocompleteProvider(nil, t.TempDir(), "")
	if provider.ShouldTriggerFileCompletion([]string{"/cmd"}, 0, 4) {
		t.Fatal("slash command must not trigger file completion")
	}
	if !provider.ShouldTriggerFileCompletion([]string{"/cmd arg"}, 0, 8) {
		t.Fatal("slash command argument must trigger file completion")
	}
	if suggestions := provider.GetSuggestions(context.Background(), []string{"@x"}, 0, 2, false); suggestions != nil {
		t.Fatalf("no fd should return no suggestions: %+v", suggestions)
	}
}

// TestAutocompleteFuzzyScoring covers the score ordering without fd.
func TestAutocompleteFuzzyScoring(t *testing.T) {
	provider := NewCombinedAutocompleteProvider(nil, t.TempDir(), "")
	exact := provider.scoreEntry("src/alpha.txt", "alpha.txt", false)
	prefix := provider.scoreEntry("src/alphabeta.txt", "alpha", false)
	substring := provider.scoreEntry("src/xalpha.txt", "alpha", false)
	pathOnly := provider.scoreEntry("src/alpha/z.txt", "alpha", false)
	dirBonus := provider.scoreEntry("src/alpha", "alpha", true)
	if !(exact > prefix && prefix > substring && substring > pathOnly) {
		t.Fatalf("scores: %d %d %d %d", exact, prefix, substring, pathOnly)
	}
	if dirBonus <= prefix {
		t.Fatalf("directory bonus missing: %d vs %d", dirBonus, prefix)
	}
	if provider.scoreEntry("src/x.txt", "nomatch", false) != 0 {
		t.Fatal("non-matching entry scored")
	}
}

// TestAutocompleteCompletesCommandsAfterLeadingWhitespace ports
// autocomplete-skill-slash.test.ts (65117e31f, #10218): command completion
// works after leading whitespace, which is preserved, and argument completion
// sees the trimmed argument text.
func TestAutocompleteCompletesCommandsAfterLeadingWhitespace(t *testing.T) {
	provider := NewCombinedAutocompleteProvider([]CommandEntry{{Name: "model"}}, ".", "")
	for _, testCase := range []struct{ line, expected string }{
		{" /", " /model "},
		{"  /mod", "  /model "},
		{"\t/mod", "\t/model "},
	} {
		result := provider.GetSuggestions(context.Background(), []string{testCase.line}, 0, len(testCase.line), false)
		if result == nil {
			t.Fatalf("%q: no suggestions", testCase.line)
		}
		if result.Prefix != strings.TrimLeft(testCase.line, " \t") {
			t.Fatalf("%q: prefix = %q", testCase.line, result.Prefix)
		}
		if len(result.Items) != 1 || result.Items[0].Value != "model" {
			t.Fatalf("%q: items = %+v", testCase.line, result.Items)
		}
		applied := provider.ApplyCompletion([]string{testCase.line}, 0, len(testCase.line), result.Items[0], result.Prefix)
		if applied.Lines[0] != testCase.expected || applied.CursorCol != len(testCase.expected) {
			t.Fatalf("%q: applied = %q@%d, want %q@%d",
				testCase.line, applied.Lines[0], applied.CursorCol, testCase.expected, len(testCase.expected))
		}
	}
}

// TestAutocompleteCompletesArgumentsAfterLeadingWhitespace is upstream's
// "completes command arguments after leading whitespace" case.
func TestAutocompleteCompletesArgumentsAfterLeadingWhitespace(t *testing.T) {
	seen := ""
	provider := NewCombinedAutocompleteProvider([]CommandEntry{{
		Name: "model",
		GetArgumentCompletions: func(prefix string) ([]AutocompleteItem, bool) {
			seen = prefix
			return []AutocompleteItem{{Value: "sonnet", Label: "sonnet"}}, true
		},
	}}, ".", "")
	line := "  /model son"
	result := provider.GetSuggestions(context.Background(), []string{line}, 0, len(line), false)
	if result == nil {
		t.Fatal("no suggestions")
	}
	if result.Prefix != "son" || seen != "son" {
		t.Fatalf("prefix = %q, argument prefix = %q", result.Prefix, seen)
	}
	applied := provider.ApplyCompletion([]string{line}, 0, len(line), result.Items[0], result.Prefix)
	if applied.Lines[0] != "  /model sonnet" {
		t.Fatalf("applied = %q", applied.Lines[0])
	}
}
