package tui

import (
	"bufio"
	"encoding/json"
	"os"
	"strconv"
	"strings"
	"sync"
	"testing"
)

// The golden file is generated by driving the upstream TuiMainScreen with a
// fake recording terminal and scripted content/size steps, then dumping the
// concatenated writes per step. The Go test replays the same steps against the
// Go main screen (tui/testdata/mainscreen_golden.txt).

type mainScreenStep struct {
	Lines      []string `json:"lines"`
	Columns    *int     `json:"columns"`
	Rows       *int     `json:"rows"`
	HideCursor *bool    `json:"hideCursor"`
	Force      bool     `json:"force"`
}

type mainScreenSpec struct {
	Steps         []mainScreenStep `json:"steps"`
	ClearOnShrink bool             `json:"clearOnShrink"`
}

// recordingTerminal captures writes and exposes mutable dimensions.
type recordingTerminal struct {
	width  int
	height int
	// mu guards writes: the renderer's timer-driven renders write from other
	// goroutines.
	mu     sync.Mutex
	writes []string
}

func (t *recordingTerminal) appendWrite(data string) {
	t.mu.Lock()
	defer t.mu.Unlock()
	t.writes = append(t.writes, data)
}

func (t *recordingTerminal) takeWrites() string {
	t.mu.Lock()
	defer t.mu.Unlock()
	joined := strings.Join(t.writes, "")
	t.writes = nil
	return joined
}

func (t *recordingTerminal) resetWrites() {
	t.mu.Lock()
	defer t.mu.Unlock()
	t.writes = nil
}

func (t *recordingTerminal) Start(onInput func(string), onResize func()) {}
func (t *recordingTerminal) Stop()                                       {}
func (t *recordingTerminal) DrainInput(maxMs int, idleMs int) error      { return nil }
func (t *recordingTerminal) Write(data string)                           { t.appendWrite(data) }
func (t *recordingTerminal) Columns() int                                { return t.width }
func (t *recordingTerminal) Rows() int                                   { return t.height }
func (t *recordingTerminal) KittyProtocolActive() bool                   { return false }
func (t *recordingTerminal) MoveBy(lines int)                            {}
func (t *recordingTerminal) HideCursor()                                 { t.appendWrite("<HIDE>") }
func (t *recordingTerminal) ShowCursor()                                 { t.appendWrite("<SHOW>") }
func (t *recordingTerminal) ClearLine()                                  {}
func (t *recordingTerminal) ClearFromCursor()                            {}
func (t *recordingTerminal) ClearScreen()                                {}
func (t *recordingTerminal) SetTitle(title string)                       {}
func (t *recordingTerminal) SetProgress(active bool)                     {}

// scriptedComponent renders the current scripted lines padded to the width.
type scriptedComponent struct {
	lines []string
}

func (c *scriptedComponent) Render(width int) []string {
	out := make([]string, 0, len(c.lines))
	for _, line := range c.lines {
		runes := []rune(line)
		if len(runes) >= width {
			out = append(out, string(runes[:width]))
		} else {
			out = append(out, line+repeatSpaces(width-len(runes)))
		}
	}
	return out
}

func (c *scriptedComponent) Invalidate() {}

// TestMainScreenAgainstUpstreamGolden replays the upstream write streams.
func TestMainScreenAgainstUpstreamGolden(t *testing.T) {
	// The renderer suppresses the full repaint on a height change under Termux
	// (see TestMainScreenTermuxHeightChange). This test asserts upstream's
	// stream, so the host's Termux-ness must not leak into it.
	t.Setenv("TERMUX_VERSION", "")
	golden := loadMainScreenGolden(t)
	data, err := os.ReadFile("testdata/mainscreen_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := map[string]mainScreenSpec{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	labels := make([]string, 0, len(corpus))
	for label := range corpus {
		labels = append(labels, label)
	}
	sortStrings(labels)

	for _, label := range labels {
		spec := corpus[label]
		terminal := &recordingTerminal{width: 20, height: 6}
		screen := NewMainScreen(terminal, false, t.TempDir())
		component := &scriptedComponent{}
		screen.AddChild(component)
		if spec.ClearOnShrink {
			screen.SetClearOnShrink(true)
		}

		var steps []string
		for _, step := range spec.Steps {
			component.lines = step.Lines
			if step.Columns != nil {
				terminal.width = *step.Columns
			}
			if step.Rows != nil {
				terminal.height = *step.Rows
			}
			if step.HideCursor != nil {
				screen.SetShowHardwareCursor(*step.HideCursor)
			}
			terminal.resetWrites()
			screen.RenderNow(step.Force)
			steps = append(steps, terminal.takeWrites())
		}

		want, ok := golden[label]
		if !ok {
			t.Fatalf("missing golden %q", label)
		}
		var wantSteps []string
		if err := json.Unmarshal([]byte(want), &wantSteps); err != nil {
			t.Fatalf("bad golden %q: %v", label, err)
		}
		if len(steps) != len(wantSteps) {
			t.Fatalf("%s: %d steps, want %d", label, len(steps), len(wantSteps))
		}
		for index := range steps {
			if steps[index] != wantSteps[index] {
				t.Fatalf("%s step %d:\n got %q\nwant %q", label, index, steps[index], wantSteps[index])
			}
		}
	}
}

func loadMainScreenGolden(t *testing.T) map[string]string {
	t.Helper()
	file, err := os.Open("testdata/mainscreen_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()
	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[strings.TrimPrefix(parts[0], "ms ")] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

// TestMainScreenHelpers covers the kitty parsing and the bounded writer.
func TestMainScreenHelpers(t *testing.T) {
	header, ok := parseKittyImageHeader("\x1b_Gi=5,r=3,a=T;payload\x1b\\")
	if !ok || header.Rows != 3 || len(header.IDs) != 1 || header.IDs[0] != 5 {
		t.Fatalf("header = %+v ok=%v", header, ok)
	}
	if header, ok := parseKittyImageHeader("plain"); ok {
		t.Fatalf("plain parsed: %+v", header)
	}
	if header, ok := parseKittyImageHeader("\x1b_Gi=0,r=-1;\x1b\\"); !ok || len(header.IDs) != 0 || header.Rows != 1 {
		t.Fatalf("invalid params parsed: %+v", header)
	}
	// Upstream caps an id at 0xffffffff (tui-main-screen.ts). The guard keeps
	// the assertion off 32-bit ints, where strconv.Atoi rejects the id first.
	if strconv.IntSize == 64 {
		if header, ok := parseKittyImageHeader("\x1b_Gi=4294967295,i=4294967296;\x1b\\"); !ok || len(header.IDs) != 1 || int64(header.IDs[0]) != kittyImageIDMax {
			t.Fatalf("id bound parsed: %+v", header)
		}
	}
	if ids := extractKittyImageIDs("\x1b_Gi=9,i=10;\x1b\\"); len(ids) != 2 || ids[0] != 9 || ids[1] != 10 {
		t.Fatalf("ids = %v", ids)
	}
	if got := DeleteKittyImage(7); got != "\x1b_Ga=d,d=I,i=7,q=2\x1b\\" {
		t.Fatalf("delete = %q", got)
	}

	var written []string
	writer := NewBoundedTerminalWriter(func(data string) { written = append(written, data) })
	writer.Append("hello")
	writer.Append(" world")
	if writer.Len() != len("hello world") {
		t.Fatalf("len = %d", writer.Len())
	}
	writer.Flush()
	if strings.Join(written, "") != "hello world" {
		t.Fatalf("written = %q", written)
	}
	if writer.Len() != len("hello world") {
		t.Fatalf("len after flush = %d", writer.Len())
	}
}

// TestMainScreenCapacity covers the shrink/clear and forced-redraw paths.
func TestMainScreenCapacity(t *testing.T) {
	terminal := &recordingTerminal{width: 10, height: 6}
	screen := NewMainScreen(terminal, false, t.TempDir())
	component := &scriptedComponent{lines: []string{"1", "2", "3", "4", "5"}}
	screen.AddChild(component)
	screen.RenderNow(false)
	first := terminal.takeWrites()
	terminal.resetWrites()

	// Shrinking to one line clears the extra lines without a full redraw.
	component.lines = []string{"1"}
	screen.RenderNow(false)
	second := terminal.takeWrites()
	if !strings.Contains(second, "\x1b[2K") || strings.Contains(second, "\x1b[2J") {
		t.Fatalf("shrink did not clear lines: %q", second)
	}

	// Content taller than the viewport forces a full redraw on shrink.
	tall := &recordingTerminal{width: 10, height: 3}
	tallScreen := NewMainScreen(tall, false, t.TempDir())
	tallComponent := &scriptedComponent{lines: []string{"1", "2", "3", "4", "5"}}
	tallScreen.AddChild(tallComponent)
	tallScreen.RenderNow(false)
	tall.resetWrites()
	tallComponent.lines = []string{"1"}
	tallScreen.RenderNow(false)
	if got := tall.takeWrites(); !strings.Contains(got, "\x1b[2J") {
		t.Fatalf("scrolled shrink did not full redraw: %q", got)
	}

	// Grow back and verify a full redraw resets the state.
	component.lines = []string{"1", "2", "3", "4", "5", "6"}
	terminal.resetWrites()
	screen.RenderNow(true)
	third := terminal.takeWrites()
	if !strings.HasPrefix(third, "\x1b[?2026h\x1b[2J\x1b[H\x1b[3J") {
		t.Fatalf("forced render did not clear: %q", third)
	}
	if first == "" || second == "" {
		t.Fatal("empty renders")
	}
	if state := screen.CaptureRenderState(); len(state.PreviousLines) != 6 {
		t.Fatalf("state lines = %d", len(state.PreviousLines))
	}
	state := screen.CaptureRenderState()
	state.PreviousLines = []string{""}
	screen.RestoreRenderState(state)
	if got := screen.CaptureRenderState(); len(got.PreviousLines) != 1 {
		t.Fatalf("restore = %d lines", len(got.PreviousLines))
	}
}

// A height change normally forces a full repaint to keep the viewport aligned.
// Under Termux the software keyboard toggles the height on every show/hide, and
// a repaint per toggle storms the scrollback, so the port skips it there. That
// divergence is deliberate (README, tui main-screen renderer); the golden test
// neutralizes TERMUX_VERSION so it still asserts upstream's stream.
func TestMainScreenTermuxHeightChange(t *testing.T) {
	render := func(t *testing.T) []string {
		t.Helper()
		terminal := &recordingTerminal{width: 20, height: 6}
		screen := NewMainScreen(terminal, false, t.TempDir())
		component := &scriptedComponent{}
		screen.AddChild(component)

		steps := []mainScreenStep{
			{Lines: []string{"a", "b", "c", "d"}},
			{Lines: []string{"a", "b", "c", "d"}, Rows: intPtr(3)},
		}
		var writes []string
		for _, step := range steps {
			component.lines = step.Lines
			if step.Rows != nil {
				terminal.height = *step.Rows
			}
			terminal.resetWrites()
			screen.RenderNow(step.Force)
			writes = append(writes, terminal.takeWrites())
		}
		return writes
	}

	t.Run("under Termux the repaint is skipped", func(t *testing.T) {
		t.Setenv("TERMUX_VERSION", "0.118")
		writes := render(t)
		if clear := "\x1b[2J\x1b[H\x1b[3J"; strings.Contains(writes[1], clear) {
			t.Errorf("height change repainted under Termux: %q", writes[1])
		}
	})

	t.Run("elsewhere the repaint happens", func(t *testing.T) {
		t.Setenv("TERMUX_VERSION", "")
		writes := render(t)
		if clear := "\x1b[2J\x1b[H\x1b[3J"; !strings.Contains(writes[1], clear) {
			t.Errorf("height change did not repaint: %q", writes[1])
		}
	})
}
