package tui

import (
	"encoding/json"
	"math"
	"os"
	"testing"
)

// Golden generated by driving upstream packages/tui/src/oklab.ts (bf8e4b953)
// with Node: OkhslToRgb over a hue/saturation/lightness grid, RgbToOkhsl over
// sample colors, and OklabToOkhslLightness.
type oklabGoldenFile struct {
	Okhsl []struct {
		H   float64  `json:"h"`
		S   float64  `json:"s"`
		L   float64  `json:"l"`
		RGB RgbColor `json:"rgb"`
	} `json:"okhsl"`
	RoundTrip []struct {
		Hex   string   `json:"hex"`
		RGB   RgbColor `json:"rgb"`
		Okhsl struct {
			H float64 `json:"h"`
			S float64 `json:"s"`
			L float64 `json:"l"`
		} `json:"okhsl"`
	} `json:"roundTrip"`
	Lightness []struct {
		X float64 `json:"x"`
		Y float64 `json:"y"`
	} `json:"lightness"`
	Oklch []struct {
		Hex   string   `json:"hex"`
		RGB   RgbColor `json:"rgb"`
		Oklch struct {
			L float64 `json:"l"`
			C float64 `json:"c"`
			H float64 `json:"h"`
		} `json:"oklch"`
	} `json:"oklch"`
}

func loadOklabGolden(t *testing.T) oklabGoldenFile {
	t.Helper()
	data, err := os.ReadFile("testdata/oklab_golden.json")
	if err != nil {
		t.Fatal(err)
	}
	var golden oklabGoldenFile
	if err := json.Unmarshal(data, &golden); err != nil {
		t.Fatal(err)
	}
	return golden
}

func TestOkhslToRgbAgainstUpstreamGolden(t *testing.T) {
	golden := loadOklabGolden(t)
	for _, c := range golden.Okhsl {
		if got := OkhslToRgb(c.H, c.S, c.L); got != c.RGB {
			t.Fatalf("OkhslToRgb(%v, %v, %v) = %+v (want %+v)", c.H, c.S, c.L, got, c.RGB)
		}
	}
}

func TestRgbToOkhslAgainstUpstreamGolden(t *testing.T) {
	golden := loadOklabGolden(t)
	for _, c := range golden.RoundTrip {
		channels := RgbToOkhsl(c.RGB)
		if math.Abs(channels.H-c.Okhsl.H) > 1e-6 || math.Abs(channels.S-c.Okhsl.S) > 1e-6 || math.Abs(channels.L-c.Okhsl.L) > 1e-6 {
			t.Fatalf("RgbToOkhsl(%s) = %+v (want %+v)", c.Hex, channels, c.Okhsl)
		}
		if got := OkhslToRgb(channels.H, channels.S, channels.L); got != c.RGB {
			t.Fatalf("round trip %s = %+v (want %+v)", c.Hex, got, c.RGB)
		}
	}
}

func TestRgbToOklchAgainstUpstreamGolden(t *testing.T) {
	golden := loadOklabGolden(t)
	for _, c := range golden.Oklch {
		channels := RgbToOklch(c.RGB)
		if math.Abs(channels.L-c.Oklch.L) > 1e-12 || math.Abs(channels.C-c.Oklch.C) > 1e-12 {
			t.Fatalf("RgbToOklch(%s) = %+v (want %+v)", c.Hex, channels, c.Oklch)
		}
		// Hue is undefined for achromatic colors: the near-zero a/b components
		// carry only float noise, so compare it only above a chroma threshold.
		if c.Oklch.C <= 1e-7 {
			continue
		}
		if math.Abs(channels.H-c.Oklch.H) > 1e-6 {
			t.Fatalf("RgbToOklch(%s) hue = %v (want %v)", c.Hex, channels.H, c.Oklch.H)
		}
	}
}

func TestOklabToOkhslLightnessAgainstUpstreamGolden(t *testing.T) {
	golden := loadOklabGolden(t)
	for _, c := range golden.Lightness {
		if got := OklabToOkhslLightness(c.X); math.Abs(got-c.Y) > 1e-9 {
			t.Fatalf("OklabToOkhslLightness(%v) = %v (want %v)", c.X, got, c.Y)
		}
	}
}
