package tui

import (
	"encoding/json"
	"os"
	"testing"
)

// Golden generated by driving upstream packages/tui/src/colors.ts (bf8e4b953)
// with Node: OklchToRgb over a lightness/chroma/hue grid and ParseColor over
// hex, oklch() and okhsl() values.
type oklchGoldenFile struct {
	Oklch []struct {
		L   float64  `json:"l"`
		C   float64  `json:"c"`
		H   float64  `json:"h"`
		RGB RgbColor `json:"rgb"`
	} `json:"oklch"`
	Parse []struct {
		Value string   `json:"value"`
		RGB   RgbColor `json:"rgb"`
	} `json:"parse"`
}

func TestOklchAgainstUpstreamGolden(t *testing.T) {
	data, err := os.ReadFile("testdata/oklch_golden.json")
	if err != nil {
		t.Fatal(err)
	}
	var golden oklchGoldenFile
	if err := json.Unmarshal(data, &golden); err != nil {
		t.Fatal(err)
	}
	for _, c := range golden.Oklch {
		if got := OklchToRgb(c.L, c.C, c.H); got != c.RGB {
			t.Fatalf("OklchToRgb(%v, %v, %v) = %+v (want %+v)", c.L, c.C, c.H, got, c.RGB)
		}
	}
	for _, c := range golden.Parse {
		got, ok := ParseColor(c.Value)
		if !ok || got != c.RGB {
			t.Fatalf("ParseColor(%q) = %+v, %v (want %+v)", c.Value, got, ok, c.RGB)
		}
	}
	if _, ok := ParseColor("someVariable"); ok {
		t.Fatal("a variable reference parsed as a color")
	}
}
