package interactive

import (
	"bufio"
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/dat267/pier/coding"
	"github.com/dat267/pier/tui"
)

// The golden file is generated by running the upstream bash-execution and
// tool-execution components with Node
// (coding/interactive/testdata/exec_golden.txt).

type bashSpec struct {
	Command    string   `json:"command"`
	Chunks     []string `json:"chunks"`
	ExitCode   *int     `json:"exitCode"`
	Complete   bool     `json:"complete"`
	Error      bool     `json:"error"`
	Cancelled  bool     `json:"cancelled"`
	Truncation *struct {
		Truncated bool `json:"truncated"`
	} `json:"truncation"`
	FullOutputPath string `json:"fullOutputPath"`
	Expanded       bool   `json:"expanded"`
	Exclude        bool   `json:"exclude"`
	Running        bool   `json:"running"`
	Width          int    `json:"width"`
}

type toolResultSpec struct {
	Content []ToolResultContent `json:"content"`
	IsError bool                `json:"isError"`
}

type toolSpec struct {
	Name             string          `json:"name"`
	Args             json.RawMessage `json:"args"`
	Width            int             `json:"width"`
	Result           *toolResultSpec `json:"result"`
	IsPartial        *bool           `json:"isPartial"`
	Expanded         bool            `json:"expanded"`
	ExpandAfter      bool            `json:"expandAfter"`
	ExecutionStarted bool            `json:"executionStarted"`
	ArgsComplete     bool            `json:"argsComplete"`
	NoDefinition     bool            `json:"noDefinition"`
	SelfShell        bool            `json:"selfShell"`
	CallRenderer     string          `json:"callRenderer"`
	ResultRenderer   string          `json:"resultRenderer"`
}

type execCorpus struct {
	Bash map[string]bashSpec `json:"bash"`
	Tool map[string]toolSpec `json:"tool"`
}

func loadExecGolden(t *testing.T) map[string]string {
	t.Helper()
	file, err := os.Open("testdata/exec_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()
	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[strings.TrimPrefix(parts[0], "e ")] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

func checkExecGolden(t *testing.T, golden map[string]string, label string, got any) {
	t.Helper()
	if lines, ok := got.([]string); ok && lines == nil {
		got = []string{}
	}
	want, ok := golden[label]
	if !ok {
		t.Fatalf("missing golden %q", label)
	}
	gotStable := stableMDValue(mustParseJSON(t, mustJSON(got)))
	wantStable := stableMDValue(mustParseJSON(t, want))
	if gotStable != wantStable {
		t.Fatalf("%s:\n got %s\nwant %s", label, gotStable, wantStable)
	}
}

// TestExecComponentsAgainstUpstreamGolden replays the bash/tool components.
func TestExecComponentsAgainstUpstreamGolden(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	golden := loadExecGolden(t)
	data, err := os.ReadFile("testdata/exec_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := execCorpus{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	for _, label := range sortedKeys(corpus.Bash) {
		spec := corpus.Bash[label]
		component := NewBashExecutionComponent(spec.Command, nil, spec.Exclude, 1)
		for _, chunk := range spec.Chunks {
			component.AppendOutput(chunk)
		}
		completed := spec.Complete || spec.Error || spec.Cancelled
		if completed {
			truncation := coding.TruncationResult{Truncated: spec.Truncation != nil && spec.Truncation.Truncated}
			component.SetComplete(spec.ExitCode, spec.Cancelled, &truncation, spec.FullOutputPath)
		}
		if spec.Expanded {
			component.SetExpanded(true)
		}
		if spec.Running {
			checkExecGolden(t, golden, "bash "+label+"-running@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
		}
		checkExecGolden(t, golden, "bash "+label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
		checkExecGolden(t, golden, "bash "+label+"-output", component.GetOutput())
	}

	for _, label := range sortedKeys(corpus.Tool) {
		spec := corpus.Tool[label]
		var definition *ToolRenderers
		if !spec.NoDefinition {
			definition = &ToolRenderers{}
			if spec.SelfShell {
				definition.RenderShell = "self"
			}
			if spec.CallRenderer == "throw" {
				definition.RenderCall = func(args any, theme *Theme, context *ToolRenderContext) tui.Component {
					panic("call boom")
				}
			} else {
				encoded, _ := json.Marshal(spec.Args)
				definition.RenderCall = func(args any, theme *Theme, context *ToolRenderContext) tui.Component {
					return tui.NewText("call:"+string(encoded), 0, 0, nil)
				}
			}
			switch spec.ResultRenderer {
			case "throw":
				definition.RenderResult = func(result *SortToolResultContent, options ToolRenderResultOptions, theme *Theme, context *ToolRenderContext) tui.Component {
					panic("result boom")
				}
			case "none":
			default:
				definition.RenderResult = func(result *SortToolResultContent, options ToolRenderResultOptions, theme *Theme, context *ToolRenderContext) tui.Component {
					state := "collapsed"
					if options.Expanded {
						state = "expanded"
					}
					partial := "final"
					if options.IsPartial {
						partial = "partial"
					}
					var texts []string
					for _, content := range result.Content {
						if content.Type == "text" {
							texts = append(texts, content.Text)
						}
					}
					return tui.NewText("result:"+state+":"+partial+":"+strings.Join(texts, "|"), 0, 0, nil)
				}
			}
		}

		var args any
		if len(spec.Args) > 0 {
			_ = json.Unmarshal(spec.Args, &args)
		}
		showImages := true
		component := NewToolExecutionComponent(spec.Name, "call-1", args, ToolExecutionOptions{ShowImages: &showImages}, definition, nil, "/tmp")
		if spec.ExecutionStarted {
			component.MarkExecutionStarted()
		}
		if spec.ArgsComplete {
			component.SetArgsComplete()
		}
		if spec.Result != nil {
			isPartial := false
			if spec.IsPartial != nil {
				isPartial = *spec.IsPartial
			}
			component.UpdateResult(&SortToolResultContent{Content: spec.Result.Content, IsError: spec.Result.IsError}, isPartial)
		}
		if spec.Expanded {
			component.SetExpanded(true)
		}
		checkExecGolden(t, golden, "tool "+label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
		if spec.ExpandAfter {
			component.SetExpanded(true)
			checkExecGolden(t, golden, "tool "+label+"-expanded@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
		}
	}
}

func sortedKeys[V any](values map[string]V) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sortStrings(keys)
	return keys
}

// TestExecHelpers covers the render utilities.
func TestExecHelpers(t *testing.T) {
	home, _ := os.UserHomeDir()
	if got := ShortenPath(home + "/file.txt"); got != "~/file.txt" {
		t.Fatalf("ShortenPath = %q", got)
	}
	if got := ShortenPath("/other/file.txt"); got != "/other/file.txt" {
		t.Fatalf("ShortenPath = %q", got)
	}
	if value, ok := Str(nil); !ok || value != "" {
		t.Fatalf("Str(nil) = %q %v", value, ok)
	}
	if _, ok := Str(42); ok {
		t.Fatal("Str(42) accepted")
	}
	if got := NormalizeDisplayText("a\rb"); got != "ab" {
		t.Fatalf("NormalizeDisplayText = %q", got)
	}
	if got := ReplaceTabsLocal("a\tb"); got != "a   b" {
		t.Fatalf("replaceTabs = %q", got)
	}

	result := &SortToolResultContent{Content: []ToolResultContent{
		{Type: "text", Text: "\x1b[31mred\x1b[0m text"},
		{Type: "image", Data: "AAAA", MimeType: "image/png"},
	}}
	SetTrueColorSupport(true)
	output := GetTextOutput(result, true)
	if !strings.Contains(output, "red text") || strings.Contains(output, "\x1b") {
		t.Fatalf("output = %q", output)
	}
	if !strings.Contains(output, "[Image: image/png]") {
		t.Fatalf("image fallback missing: %q", output)
	}
}

func ReplaceTabsLocal(value string) string { return strings.ReplaceAll(value, "\t", "   ") }

// backgroundFills extracts the background *fills* of a rendered block (the
// \x1b[48;…m sequences), ignoring the \x1b[49m reset that every styled run ends
// with: the caller can then ask whether a block is filled at all, and whether
// two blocks are filled the same.
func backgroundFills(lines []string) []string {
	var found []string
	for _, line := range lines {
		for _, seq := range ansiSequenceRe.FindAllString(line, -1) {
			if strings.HasPrefix(seq, "\x1b[48;") {
				found = append(found, seq)
			}
		}
	}
	return found
}

// A tool call has to look different while it runs, when it succeeds and when it
// fails. Upstream picks toolPendingBg / toolSuccessBg / toolErrorBg in
// components/tool-execution.ts (updateDisplay) and pi-tui's Box fills the whole
// block with it; the port does the same in toolexecution.go. The corpus above
// pins that with the embedded upstream palette, which is not what the CLI
// installs — so this renders the three states with the port's own palette
// (D154), where the signal had gone missing.
func TestToolExecutionBackgroundsSignalState(t *testing.T) {
	installPierThemeForTest(t)
	t.Cleanup(func() { SetRegisteredThemes(nil) })

	render := func(isPartial bool, isError bool) []string {
		definition := builtinToolRenderers["bash"]
		component := NewToolExecutionComponent("bash", "call-1", map[string]any{"command": "ls"}, ToolExecutionOptions{}, &definition, nil, "/tmp")
		component.MarkExecutionStarted()
		component.SetArgsComplete()
		component.UpdateResult(&SortToolResultContent{
			Content: []ToolResultContent{{Type: "text", Text: "one\ntwo"}},
			IsError: isError,
		}, isPartial)
		return component.Render(40)
	}

	states := []struct {
		label   string
		partial bool
		err     bool
	}{
		{"pending", true, false},
		{"success", false, false},
		{"failed", false, true},
	}
	for _, name := range []string{"dark", "light"} {
		t.Run(name, func(t *testing.T) {
			InitTheme(name, false)
			blocks := map[string]string{}
			fills := map[string]string{}
			for _, state := range states {
				lines := render(state.partial, state.err)
				blocks[state.label] = strings.Join(lines, "\n")
				got := backgroundFills(lines)
				if len(got) == 0 {
					t.Fatalf("%s: the block is not filled at all", state.label)
				}
				for _, fill := range got {
					if fill != got[0] {
						t.Errorf("%s: mixed fills %q and %q in one block", state.label, got[0], fill)
						break
					}
				}
				fills[state.label] = got[0]
			}
			for i, a := range states {
				for _, b := range states[i+1:] {
					if blocks[a.label] == blocks[b.label] {
						t.Errorf("%s and %s render identically", a.label, b.label)
					}
					if fills[a.label] == fills[b.label] {
						t.Errorf("%s and %s are filled the same (%s)", a.label, b.label, fills[a.label])
					}
				}
			}
		})
	}
}
