package interactive

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/dat267/pier/ai"
	"github.com/dat267/pier/coding"
	"github.com/dat267/pier/tui"
)

// The golden file is generated by running the upstream footer component with
// Node (coding/interactive/testdata/footer_golden.txt). Both sides load the
// same session JSONL fixture. The upstream FOOTER RENDER golden checks were
// removed with D141: the builtin footer renders the user's extension format.
// The extension's own format.test.ts cases are ported below.

type footerCorpus struct {
	Tokens map[string]struct {
		Count int64 `json:"count"`
	} `json:"tokens"`
	Cwd map[string]struct {
		Cwd  string `json:"cwd"`
		Home string `json:"home"`
	} `json:"cwd"`
}

// fakeFooterSession implements FooterSession over a real session manager.
type fakeFooterSession struct {
	manager       *coding.SessionManager
	model         *ai.Model
	thinkingLevel string
	contextUsage  *coding.ContextUsageReport
	subscriptions map[string]bool
}

func (f *fakeFooterSession) Model() *ai.Model { return f.model }

func (f *fakeFooterSession) ThinkingLevel() ai.ThinkingLevel { return f.thinkingLevel }

func (f *fakeFooterSession) SessionManager() *coding.SessionManager { return f.manager }

func (f *fakeFooterSession) GetContextUsage() *coding.ContextUsageReport { return f.contextUsage }

func (f *fakeFooterSession) IsUsingSubscription(providerID string) bool {
	return f.subscriptions[providerID]
}

// fakeFooterData implements coding.ReadonlyFooterDataProvider.
type fakeFooterData struct {
	branch        string
	hasBranch     bool
	statuses      map[string]string
	providerCount int
}

func (f *fakeFooterData) GetGitBranch() (string, bool) { return f.branch, f.hasBranch }

func (f *fakeFooterData) GetExtensionStatuses() map[string]string { return f.statuses }

func (f *fakeFooterData) GetAvailableProviderCount() int { return f.providerCount }

func (f *fakeFooterData) OnBranchChange(func()) func() { return func() {} }

// TestFooterHelpersAgainstUpstreamGolden replays the pure formatting helpers
// that keep their upstream behavior.
func TestFooterHelpersAgainstUpstreamGolden(t *testing.T) {
	// The cwd corpus is Unix data (POSIX paths) fed to FormatCwdForFooter, which
	// mirrors Node's path.relative and is therefore platform-sensitive: on
	// Windows the same inputs render with the platform separator, so the Unix
	// golden cannot match.
	if runtime.GOOS == "windows" {
		t.Skip("the cwd corpus is Unix data for a platform-sensitive helper")
	}
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	golden := loadGoldenFile(t, "testdata/footer_golden.txt")
	data, err := os.ReadFile("testdata/footer_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := footerCorpus{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	for _, label := range sortedKeys(corpus.Tokens) {
		checkEasterGolden(t, golden, "tokens "+label, FormatTokens(corpus.Tokens[label].Count))
	}
	for _, label := range sortedKeys(corpus.Cwd) {
		spec := corpus.Cwd[label]
		checkEasterGolden(t, golden, "cwd "+label, FormatCwdForFooter(spec.Cwd, spec.Home))
	}
}

// TestFormatTokensSimple ports the footer extension's formatTokens boundaries
// (format.test.ts).
func TestFormatTokensSimple(t *testing.T) {
	cases := []struct {
		count int64
		want  string
	}{
		{999, "999"},
		{1000, "1.0k"},
		{9900, "9.9k"},
		{10000, "10k"},
		{999999, "1000k"},
		{1000000, "1M"},
		{2500000, "3M"},
	}
	for _, c := range cases {
		if got := FormatTokensSimple(c.count); got != c.want {
			t.Errorf("FormatTokensSimple(%d) = %q, want %q", c.count, got, c.want)
		}
	}
}

// TestFooterTruncate ports format.test.ts truncate cases.
func TestFooterTruncate(t *testing.T) {
	if got := FooterTruncate("abc", 10); got != "abc" {
		t.Errorf("short pass-through = %q", got)
	}
	if got := FooterTruncate("abcdefghij", 6); len(got) > 6 || got[len(got)-3:] != "..." {
		t.Errorf("ellipsized = %q", got)
	}
	if got := FooterTruncate("abcdef", 2); got != ".." {
		t.Errorf("max 2 = %q", got)
	}
	if got := FooterTruncate("abcdef", 0); got != "" {
		t.Errorf("max 0 = %q", got)
	}
}

// TestFooterTruncateLeft ports format.test.ts truncateLeft cases.
func TestFooterTruncateLeft(t *testing.T) {
	if got := FooterTruncateLeft("abcdefghij", 8); got != "...fghij" {
		t.Errorf("truncateLeft = %q", got)
	}
	if got := FooterTruncateLeft("abc", 10); got != "abc" {
		t.Errorf("short pass-through = %q", got)
	}
	if got := FooterTruncateLeft("abcdef", 2); got != ".." {
		t.Errorf("max 2 = %q", got)
	}
	if got := FooterTruncateLeft("abcdef", 0); got != "" {
		t.Errorf("max 0 = %q", got)
	}
}

// TestFooterLine ports format.test.ts footerLine cases.
func TestFooterLine(t *testing.T) {
	usage := &coding.ContextUsageReport{
		Tokens: nil, ContextWindow: 1000000, Percent: floatPtr(3.456),
	}
	base := FooterInput{Cwd: "/home/dat/proj", ModelID: "deepseek-v4-flash"}

	// Joins context, model, cwd with · and clamps to width.
	line := FooterLine(withUsage(base, usage), 200)
	if line != "3.5%/1M · deepseek-v4-flash · proj" {
		t.Fatalf("footerLine = %q", line)
	}

	// Uses ? fallback when no usage.
	noUsage := base
	noUsage.ModelWindow = 1000000
	if line := FooterLine(noUsage, 200); line != "?/1M · deepseek-v4-flash · proj" {
		t.Fatalf("no-usage line = %q", line)
	}

	// Truncates the whole line to width.
	clamped := FooterLine(withUsage(base, usage), 20)
	if width := tui.VisibleWidth(clamped); width > 20 {
		t.Fatalf("clamped line width = %d: %q", width, clamped)
	}

	// Statuses sit after the context count, before the model.
	withStatus := withUsage(base, usage)
	withStatus.Statuses = []string{"yolo"}
	if line := FooterLine(withStatus, 200); line != "3.5%/1M · yolo · deepseek-v4-flash · proj" {
		t.Fatalf("status line = %q", line)
	}

	// Absent or empty statuses change nothing.
	expected := "3.5%/1M · deepseek-v4-flash · proj"
	emptyStatus := withUsage(base, usage)
	emptyStatus.Statuses = []string{"", ""}
	if line := FooterLine(emptyStatus, 200); line != expected {
		t.Fatalf("empty statuses line = %q", line)
	}

	// Statuses are part of the truncated line.
	fifty := &coding.ContextUsageReport{ContextWindow: 1000000, Percent: floatPtr(50)}
	twoStatuses := withUsage(base, fifty)
	twoStatuses.Statuses = []string{"yolo", "second-status"}
	line = FooterLine(twoStatuses, 24)
	if width := tui.VisibleWidth(line); width > 24 {
		t.Fatalf("line must clamp: got %q (width %d)", line, width)
	}
	if !startsWith(line, "50.0%/1M · yolo") {
		t.Fatalf("context and first status survive: got %q", line)
	}
}

func withUsage(input FooterInput, usage *coding.ContextUsageReport) FooterInput {
	input.ContextUsage = usage
	return input
}

func startsWith(line, prefix string) bool {
	return len(line) >= len(prefix) && line[:len(prefix)] == prefix
}

// TestFooterComponentRendersSingleDimLine covers the composed footer render.
func TestFooterComponentRendersSingleDimLine(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	footerProbeSessionPath := filepath.Join(t.TempDir(), "session.jsonl")
	manager, err := coding.OpenSession(footerProbeSessionPath, "", "")
	if err != nil {
		// The probe session is written by the golden test; recreate it minimally.
		if writeErr := os.WriteFile(footerProbeSessionPath, []byte("{\"type\":\"session\",\"id\":\"s\",\"cwd\":\"/p\",\"version\":\"1\"}\n"), 0o644); writeErr != nil {
			t.Fatalf("write probe session: %v", writeErr)
		}
		manager, err = coding.OpenSession(footerProbeSessionPath, "", "")
		if err != nil {
			t.Fatalf("open session: %v", err)
		}
	}
	session := &fakeFooterSession{
		manager:       manager,
		model:         &ai.Model{ID: "deepseek-v4-flash", ContextWindow: 1000000},
		thinkingLevel: "high",
	}
	footer := NewFooterComponent(session, &fakeFooterData{statuses: map[string]string{}})
	lines := footer.Render(200)
	if len(lines) != 1 {
		t.Fatalf("lines = %d, want 1", len(lines))
	}
	expected := "?/1M · deepseek-v4-flash · " + filepath.Base(manager.GetCwd())
	if got := coding.StripAnsi(lines[0]); got != expected {
		t.Fatalf("footer = %q, want %q", got, expected)
	}
}

// TestAgentSessionSatisfiesFooterSession guards the seam.
func TestAgentSessionSatisfiesFooterSession(t *testing.T) {
	var _ FooterSession = (*coding.AgentSession)(nil)
}

func floatPtr(v float64) *float64 { return &v }
