package interactive

import (
	"bufio"
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/dat267/pier/ai"
	"github.com/dat267/pier/tui"
)

// The golden file is generated by running the upstream message components with
// Node (coding/interactive/testdata/message_golden.txt).

type assistantSpec struct {
	Content        []map[string]any `json:"content"`
	StopReason     string           `json:"stopReason"`
	ErrorMessage   *string          `json:"errorMessage"`
	HideThinking   bool             `json:"hideThinking"`
	ExpandThinking *bool            `json:"expandThinking"`
	Width          int              `json:"width"`
}

type summarySpec struct {
	Summary string `json:"summary"`
	Width   int    `json:"width"`
}

type messageCorpus struct {
	Assistant  map[string]assistantSpec `json:"assistant"`
	Branch     map[string]summarySpec   `json:"branch"`
	Compaction map[string]summarySpec   `json:"compaction"`
}

func loadMessageGolden(t *testing.T) map[string]string {
	t.Helper()
	file, err := os.Open("testdata/message_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()
	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[strings.TrimPrefix(parts[0], "m ")] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

func checkMessageGolden(t *testing.T, golden map[string]string, label string, got any) {
	t.Helper()
	if lines, ok := got.([]string); ok && lines == nil {
		got = []string{}
	}
	want, ok := golden[label]
	if !ok {
		t.Fatalf("missing golden %q", label)
	}
	gotStable := stableMDValue(mustParseJSON(t, mustJSON(got)))
	wantStable := stableMDValue(mustParseJSON(t, want))
	if gotStable != wantStable {
		t.Fatalf("%s:\n got %s\nwant %s", label, gotStable, wantStable)
	}
}

func assistantMessageFromSpec(spec assistantSpec) *ai.AssistantMessage {
	message := &ai.AssistantMessage{
		API: "openai", Provider: "openai", Model: "gpt",
		StopReason: ai.StopReason(spec.StopReason), ErrorMessage: spec.ErrorMessage,
	}
	if message.StopReason == "" {
		message.StopReason = "stop"
	}
	for _, raw := range spec.Content {
		blockType, _ := raw["type"].(string)
		switch blockType {
		case "text":
			text, _ := raw["text"].(string)
			message.Content = append(message.Content, ai.TextContent{Text: text})
		case "thinking":
			thinking, _ := raw["thinking"].(string)
			message.Content = append(message.Content, ai.ThinkingContent{Thinking: thinking})
		case "toolCall":
			id, _ := raw["id"].(string)
			name, _ := raw["name"].(string)
			message.Content = append(message.Content, ai.ToolCall{ID: id, Name: name, Arguments: json.RawMessage(`{}`)})
		}
	}
	return message
}

// TestMessagesAgainstUpstreamGolden replays the upstream transcript components.
func TestMessagesAgainstUpstreamGolden(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	golden := loadMessageGolden(t)
	data, err := os.ReadFile("testdata/message_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := messageCorpus{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	assistantLabels := make([]string, 0, len(corpus.Assistant))
	for label := range corpus.Assistant {
		assistantLabels = append(assistantLabels, label)
	}
	sortStrings(assistantLabels)
	for _, label := range assistantLabels {
		spec := corpus.Assistant[label]
		component := NewAssistantMessageComponent(assistantMessageFromSpec(spec), spec.HideThinking, nil, "", 1, nil)
		checkMessageGolden(t, golden, "assistant "+label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
		if spec.ExpandThinking != nil {
			component.SetHideThinkingBlock(*spec.ExpandThinking)
			checkMessageGolden(t, golden, "assistant "+label+"-toggled@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
		}
	}

	branchLabels := make([]string, 0, len(corpus.Branch))
	for label := range corpus.Branch {
		branchLabels = append(branchLabels, label)
	}
	sortStrings(branchLabels)
	for _, label := range branchLabels {
		spec := corpus.Branch[label]
		component := NewBranchSummaryMessageComponent(spec.Summary, nil)
		checkMessageGolden(t, golden, "branch "+label+"@"+itoa(spec.Width), component.Render(spec.Width))
		component.SetExpanded(true)
		checkMessageGolden(t, golden, "branch "+label+"-expanded@"+itoa(spec.Width), component.Render(spec.Width))
	}

	compactionLabels := make([]string, 0, len(corpus.Compaction))
	for label := range corpus.Compaction {
		compactionLabels = append(compactionLabels, label)
	}
	sortStrings(compactionLabels)
	for _, label := range compactionLabels {
		spec := corpus.Compaction[label]
		component := NewCompactionSummaryMessageComponent(spec.Summary, 1234, nil)
		checkMessageGolden(t, golden, "compaction "+label+"@"+itoa(spec.Width), component.Render(spec.Width))
		component.SetExpanded(true)
		checkMessageGolden(t, golden, "compaction "+label+"-expanded@"+itoa(spec.Width), component.Render(spec.Width))
	}

	// Status indicators.
	working := NewWorkingStatusIndicator(nil, "Working...", nil, nil)
	working.Dispose()
	checkMessageGolden(t, golden, "status working", []any{
		working.Render(30), working.RenderInBorder(20), working.RenderSpinnerInBorder(5),
	})
	retry := NewRetryStatusIndicator(nil, 2, 5, 3000)
	retry.Dispose()
	checkMessageGolden(t, golden, "status retry", retry.Render(60))
	compactionStatus := NewCompactionStatusIndicator(nil, "threshold")
	compactionStatus.Dispose()
	checkMessageGolden(t, golden, "status compaction", compactionStatus.Render(60))
	branchStatus := NewBranchSummaryStatusIndicator(nil)
	branchStatus.Dispose()
	checkMessageGolden(t, golden, "status branch", branchStatus.Render(60))
	checkMessageGolden(t, golden, "status idle", IdleStatus{}.Render(8))
}

// TestAppKeybindings covers the keybinding table, the platform variants, the
// migration, and the config file.
func TestAppKeybindings(t *testing.T) {
	definitions, order := KeybindingsFor("linux", func(string) string { return "" })
	if len(order) != tuiKeybindingCount()+len(AppKeybindingNames) {
		t.Fatalf("order length = %d", len(order))
	}
	if keys := definitions["app.interrupt"].DefaultKeys; len(keys) != 1 || keys[0] != "escape" {
		t.Fatalf("app.interrupt = %v", keys)
	}
	if keys := definitions["app.message.followUp"].DefaultKeys; len(keys) != 1 || keys[0] != "alt+enter" {
		t.Fatalf("followUp = %v", keys)
	}
	if keys := definitions["tui.altScreen.search"].DefaultKeys; len(keys) != 1 || keys[0] != "ctrl+shift+f" {
		t.Fatalf("search = %v", keys)
	}
	if keys := definitions["tui.editor.undo"].DefaultKeys; len(keys) != 1 || keys[0] != "ctrl+-" {
		t.Fatalf("undo = %v", keys)
	}

	// Windows variants.
	winDefinitions, _ := KeybindingsFor("windows", func(string) string { return "" })
	if keys := winDefinitions["tui.editor.undo"].DefaultKeys; keys[0] != "ctrl+z" {
		t.Fatalf("windows undo = %v", keys)
	}
	if keys := winDefinitions["app.message.followUp"].DefaultKeys; keys[0] != "ctrl+q" {
		t.Fatalf("windows followUp = %v", keys)
	}
	if keys := winDefinitions["app.suspend"].DefaultKeys; len(keys) != 0 {
		t.Fatalf("windows suspend = %v", keys)
	}
	if keys := winDefinitions["tui.altScreen.search"].DefaultKeys; keys[0] != "ctrl+f" {
		t.Fatalf("windows search = %v", keys)
	}

	// WSL uses the Windows variants.
	if !UseWindowsKeybindings("linux", func(key string) string {
		if key == "WSL_DISTRO_NAME" {
			return "Ubuntu"
		}
		return ""
	}) {
		t.Fatal("WSL not detected")
	}
	if UseWindowsKeybindings("linux", func(string) string { return "" }) {
		t.Fatal("plain linux detected as WSL")
	}

	// macOS arrow ordering.
	macDefinitions, _ := KeybindingsFor("darwin", func(string) string { return "" })
	if keys := macDefinitions["app.tree.foldOrUp"].DefaultKeys; keys[0] != "alt+left" {
		t.Fatalf("darwin foldOrUp = %v", keys)
	}

	// Migration.
	raw := map[string]json.RawMessage{"interrupt": json.RawMessage(`"escape"`), "cursorUp": json.RawMessage(`"up"`)}
	migrated, changed := MigrateKeybindingsConfig(raw)
	if !changed {
		t.Fatal("migration not detected")
	}
	if _, ok := migrated["app.interrupt"]; !ok {
		t.Fatalf("migrated = %v", migrated)
	}
	config := ToKeybindingsConfig(migrated)
	if keys := config["app.interrupt"]; len(keys) != 1 || keys[0] != "escape" {
		t.Fatalf("config = %v", config)
	}
	if _, ok := config["nope"]; ok {
		t.Fatal("unexpected key")
	}

	// Manager overlays user bindings.
	manager := NewAppKeybindingsManager(map[string][]string{"app.interrupt": {"ctrl+q"}}, "")
	if !manager.Matches("\x11", "app.interrupt") {
		t.Fatal("user binding not applied")
	}
	if manager.Matches("\x1b", "app.interrupt") {
		t.Fatal("default binding still active")
	}
	effective := manager.GetEffectiveConfig()
	if keys := effective["app.clear"]; len(keys) != 1 || keys[0] != "ctrl+c" {
		t.Fatalf("effective = %v", keys)
	}

	// Config file loading.
	dir := t.TempDir()
	path := dir + "/keybindings.json"
	if err := os.WriteFile(path, []byte(`{"interrupt":"alt+q","app.clear":["ctrl+x"]}`), 0o644); err != nil {
		t.Fatalf("write config: %v", err)
	}
	fileManager := CreateAppKeybindings(dir)
	if !fileManager.Matches("\x1bq", "app.interrupt") {
		t.Fatal("file binding not applied")
	}
	if keys := fileManager.GetEffectiveConfig()["app.clear"]; len(keys) != 1 || keys[0] != "ctrl+x" {
		t.Fatalf("file clear = %v", keys)
	}
}

func tuiKeybindingCount() int {
	definitions, _ := KeybindingsFor("linux", func(string) string { return "" })
	count := 0
	for key := range definitions {
		if strings.HasPrefix(key, "tui.") {
			count++
		}
	}
	return count
}

// The user-message fill is the only thing that says a block is yours: upstream
// components/user-message.ts fills the box with userMessageBg and the assistant
// message has no fill at all (which is still true here). The port paints it with
// its own colour rather than upstream's, so both halves of that are worth a
// test.
func TestUserMessageBackgroundMarksYourMessages(t *testing.T) {
	installPierThemeForTest(t)
	t.Cleanup(func() { SetRegisteredThemes(nil) })

	for _, name := range []string{"dark", "light"} {
		t.Run(name, func(t *testing.T) {
			InitTheme(name, false)

			lines := NewUserMessageComponent("explain the freeze class", nil, 1, nil).Render(56)
			fills := backgroundFills(lines)
			if len(fills) == 0 {
				t.Fatalf("the user message is not filled")
			}
			for _, fill := range fills {
				if fill != fills[0] {
					t.Errorf("mixed fills %q and %q in one message", fills[0], fill)
					break
				}
			}

			assistant := NewAssistantMessageComponent(&ai.AssistantMessage{
				Content:    ai.ContentList{ai.TextContent{Text: "here you go"}},
				StopReason: ai.StopStop,
			}, false, nil, "", 1, nil)
			if other := backgroundFills(assistant.Render(56)); len(other) != 0 {
				t.Errorf("the assistant message is filled too: %v", other)
			}

			// Your message must not look like a tool call in one of its states.
			for _, key := range toolStateBackgroundColors {
				state := backgroundFills([]string{ActiveTheme().Bg(key, "x")})
				if len(state) == 0 {
					t.Fatalf("%s has no fill", key)
				}
				if state[0] == fills[0] {
					t.Errorf("the user message is filled with %s (%s)", key, fills[0])
				}
			}
		})
	}
}

// TestUserMessageKeepsOneCopyOfEachLine pins e792ba131: the Markdown pads and
// colors its own background, so the Box around it — a second full-width copy of
// every line, retained per message — is gone. The output is identical to the
// Box version's (captured before the change).
func TestUserMessageKeepsOneCopyOfEachLine(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	component := NewUserMessageComponent("hello **bold** world", nil, 1, nil)
	if children := len(component.Children); children != 1 {
		t.Fatalf("children = %d, want 1", children)
	}
	if _, isBox := component.Children[0].(*tui.Box); isBox {
		t.Fatal("the message still wraps its Markdown in a Box: a second full-width copy of every line")
	}
	want := "\x1b]133;A\a\x1b[48;2;52;53;65m                              \x1b[49m\n" +
		"\x1b[48;2;52;53;65m \x1b[38;2;212;212;212mhello \x1b[39m\x1b[1m\x1b[38;2;212;212;212mbold\x1b[39m\x1b[22m\x1b[38;2;212;212;212m\x1b[38;2;212;212;212m world\x1b[39m             \x1b[49m\n" +
		"\x1b]133;B\a\x1b]133;C\a\x1b[48;2;52;53;65m                              \x1b[49m"
	if got := strings.Join(component.Render(30), "\n"); got != want {
		t.Fatalf("render diverged:\n got  %q\n want %q", got, want)
	}
}
