package interactive

import (
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/dat267/pier/ai"
	"github.com/dat267/pier/coding"
	"github.com/dat267/pier/tui"
)

// The golden file is generated by running the upstream settings selector with
// Node (coding/interactive/testdata/settings_golden.txt).

type settingsCase struct {
	Width  int             `json:"width"`
	Inputs []string        `json:"inputs"`
	Config json.RawMessage `json:"config"`
}

type settingsCorpus struct {
	Cases map[string]settingsCase `json:"cases"`
}

type settingsConfigJSON struct {
	AutoCompact                *bool                       `json:"autoCompact"`
	DefaultModel               *string                     `json:"defaultModel"`
	ShowImages                 *bool                       `json:"showImages"`
	ImageWidthCells            *int                        `json:"imageWidthCells"`
	AutoResizeImages           *bool                       `json:"autoResizeImages"`
	BlockImages                *bool                       `json:"blockImages"`
	EnableSkillCommands        *bool                       `json:"enableSkillCommands"`
	SteeringMode               *string                     `json:"steeringMode"`
	FollowUpMode               *string                     `json:"followUpMode"`
	Transport                  *string                     `json:"transport"`
	HTTPIdleTimeoutMs          *int64                      `json:"httpIdleTimeoutMs"`
	CacheWarmingMode           *string                     `json:"cacheWarmingMode"`
	ThinkingLevel              *string                     `json:"thinkingLevel"`
	ModelThinkingLevels        map[string]string           `json:"modelThinkingLevels"`
	CurrentTheme               *string                     `json:"currentTheme"`
	TerminalTheme              *string                     `json:"terminalTheme"`
	HideThinkingBlock          *bool                       `json:"hideThinkingBlock"`
	MermaidRenderingMode       *string                     `json:"mermaidRenderingMode"`
	ShowCacheMissNotices       *bool                       `json:"showCacheMissNotices"`
	CollapseChangelog          *bool                       `json:"collapseChangelog"`
	EnableInstallTelemetry     *bool                       `json:"enableInstallTelemetry"`
	DoubleEscapeAction         *string                     `json:"doubleEscapeAction"`
	TreeFilterMode             *string                     `json:"treeFilterMode"`
	ShowHardwareCursor         *bool                       `json:"showHardwareCursor"`
	EditorPaddingX             *int                        `json:"editorPaddingX"`
	OutputPad                  *int                        `json:"outputPad"`
	AutocompleteMaxVisible     *int                        `json:"autocompleteMaxVisible"`
	QuietStartup               *coding.QuietStartupSetting `json:"quietStartup"`
	DefaultProjectTrust        *string                     `json:"defaultProjectTrust"`
	ClearOnShrink              *bool                       `json:"clearOnShrink"`
	ShowTerminalProgress       *bool                       `json:"showTerminalProgress"`
	TuiMode                    *string                     `json:"tuiMode"`
	FullscreenExitOutput       *string                     `json:"fullscreenExitOutput"`
	FullscreenScrollbar        *string                     `json:"fullscreenScrollbar"`
	FullscreenCopyOnSelect     *bool                       `json:"fullscreenCopyOnSelect"`
	FullscreenWheelScrollLines *tui.WheelScrollLines       `json:"fullscreenWheelScrollLines"`
	Warnings                   *WarningSettings            `json:"warnings"`
}

func baseSettingsConfig(t *testing.T) SettingsConfig {
	t.Helper()
	reasoning := true
	_ = reasoning
	return SettingsConfig{
		AutoCompact:  true,
		DefaultModel: "anthropic/claude-sonnet-4-5",
		CurrentModel: &ai.Model{ID: "claude-sonnet-4-5", Provider: "anthropic", Reasoning: true},
		AvailableDefaultModels: []*ai.Model{
			{ID: "gpt-5.2", Provider: "openai", Reasoning: true},
			{ID: "claude-sonnet-4-5", Provider: "anthropic", Reasoning: true},
		},
		ShowImages:                 true,
		ImageWidthCells:            80,
		AutoResizeImages:           true,
		EnableSkillCommands:        true,
		SteeringMode:               "one-at-a-time",
		FollowUpMode:               "all",
		Transport:                  "auto",
		HTTPIdleTimeoutMs:          30000,
		CacheWarmingMode:           "off",
		ThinkingLevel:              "medium",
		AvailableThinkingLevels:    []string{"off", "minimal", "low", "medium", "high"},
		ModelThinkingLevels:        map[string]string{"anthropic/claude-sonnet-4-5": "high"},
		CurrentTheme:               "dark",
		TerminalTheme:              TerminalThemeDark,
		AvailableThemes:            AvailableThemes(),
		MermaidRenderingMode:       "final",
		ShowCacheMissNotices:       true,
		CollapseChangelog:          true,
		DoubleEscapeAction:         "tree",
		TreeFilterMode:             "default",
		EditorPaddingX:             1,
		OutputPad:                  1,
		AutocompleteMaxVisible:     7,
		DefaultProjectTrust:        "ask",
		ClearOnShrink:              true,
		TuiMode:                    "regular",
		FullscreenExitOutput:       "transcript",
		FullscreenScrollbar:        "auto",
		FullscreenCopyOnSelect:     true,
		FullscreenWheelScrollLines: tui.AutoWheelScrollLines(),
		Warnings:                   WarningSettings{},
	}
}

func applySettingsJSON(t *testing.T, config *SettingsConfig, raw json.RawMessage) {
	t.Helper()
	if len(raw) == 0 || string(raw) == "null" {
		return
	}
	if string(raw) == "null" {
		return
	}
	parsed := settingsConfigJSON{}
	if err := json.Unmarshal(raw, &parsed); err != nil {
		t.Fatalf("parse config override: %v", err)
	}
	setBool := func(dst *bool, src *bool) {
		if src != nil {
			*dst = *src
		}
	}
	setString := func(dst *string, src *string) {
		if src != nil {
			*dst = *src
		}
	}
	setInt := func(dst *int, src *int) {
		if src != nil {
			*dst = *src
		}
	}
	setBool(&config.AutoCompact, parsed.AutoCompact)
	setString(&config.DefaultModel, parsed.DefaultModel)
	setBool(&config.ShowImages, parsed.ShowImages)
	setInt(&config.ImageWidthCells, parsed.ImageWidthCells)
	setBool(&config.AutoResizeImages, parsed.AutoResizeImages)
	setBool(&config.BlockImages, parsed.BlockImages)
	setBool(&config.EnableSkillCommands, parsed.EnableSkillCommands)
	setString(&config.SteeringMode, parsed.SteeringMode)
	setString(&config.FollowUpMode, parsed.FollowUpMode)
	setString(&config.Transport, parsed.Transport)
	if parsed.HTTPIdleTimeoutMs != nil {
		config.HTTPIdleTimeoutMs = *parsed.HTTPIdleTimeoutMs
	}
	setString(&config.CacheWarmingMode, parsed.CacheWarmingMode)
	setString(&config.ThinkingLevel, parsed.ThinkingLevel)
	setString(&config.CurrentTheme, parsed.CurrentTheme)
	if parsed.TerminalTheme != nil {
		config.TerminalTheme = TerminalTheme(*parsed.TerminalTheme)
	}
	setBool(&config.HideThinkingBlock, parsed.HideThinkingBlock)
	setString(&config.MermaidRenderingMode, parsed.MermaidRenderingMode)
	setBool(&config.ShowCacheMissNotices, parsed.ShowCacheMissNotices)
	setBool(&config.CollapseChangelog, parsed.CollapseChangelog)
	setBool(&config.EnableInstallTelemetry, parsed.EnableInstallTelemetry)
	setString(&config.DoubleEscapeAction, parsed.DoubleEscapeAction)
	setString(&config.TreeFilterMode, parsed.TreeFilterMode)
	setBool(&config.ShowHardwareCursor, parsed.ShowHardwareCursor)
	setInt(&config.EditorPaddingX, parsed.EditorPaddingX)
	setInt(&config.OutputPad, parsed.OutputPad)
	setInt(&config.AutocompleteMaxVisible, parsed.AutocompleteMaxVisible)
	if parsed.QuietStartup != nil {
		config.QuietStartup = *parsed.QuietStartup
	}
	setString(&config.DefaultProjectTrust, parsed.DefaultProjectTrust)
	setBool(&config.ClearOnShrink, parsed.ClearOnShrink)
	setBool(&config.ShowTerminalProgress, parsed.ShowTerminalProgress)
	setString(&config.TuiMode, parsed.TuiMode)
	setString(&config.FullscreenExitOutput, parsed.FullscreenExitOutput)
	setString(&config.FullscreenScrollbar, parsed.FullscreenScrollbar)
	setBool(&config.FullscreenCopyOnSelect, parsed.FullscreenCopyOnSelect)
	if parsed.FullscreenWheelScrollLines != nil {
		config.FullscreenWheelScrollLines = *parsed.FullscreenWheelScrollLines
	}
	if parsed.ModelThinkingLevels != nil {
		config.ModelThinkingLevels = parsed.ModelThinkingLevels
	}
	if parsed.Warnings != nil {
		config.Warnings = *parsed.Warnings
	}
}

func recordingCallbacks(events *[]string) SettingsCallbacks {
	record := func(name string) func(value string) {
		return func(value string) {
			encoded, _ := json.Marshal(value)
			*events = append(*events, name+":"+string(encoded))
		}
	}
	recordBool := func(name string) func(bool) {
		return func(value bool) {
			if value {
				*events = append(*events, name+":true")
				return
			}
			*events = append(*events, name+":false")
		}
	}
	return SettingsCallbacks{
		OnAutoCompactChange:         recordBool("onAutoCompactChange"),
		OnShowImagesChange:          recordBool("onShowImagesChange"),
		OnImageWidthCellsChange:     func(value int) { *events = append(*events, "onImageWidthCellsChange:"+itoa(value)) },
		OnAutoResizeImagesChange:    recordBool("onAutoResizeImagesChange"),
		OnBlockImagesChange:         recordBool("onBlockImagesChange"),
		OnEnableSkillCommandsChange: recordBool("onEnableSkillCommandsChange"),
		OnSteeringModeChange:        record("onSteeringModeChange"),
		OnFollowUpModeChange:        record("onFollowUpModeChange"),
		OnTransportChange: func(value ai.Transport) {
			encoded, _ := json.Marshal(value)
			*events = append(*events, "onTransportChange:"+string(encoded))
		},
		OnHTTPIdleTimeoutMsChange: func(value int64) { *events = append(*events, "onHttpIdleTimeoutMsChange:"+itoa(int(value))) },
		OnCacheWarmingModeChange:  record("onCacheWarmingModeChange"),
		OnModelThinkingLevelChange: func(provider string, modelID string, level string) {
			*events = append(*events, "onModelThinkingLevelChange:[\""+provider+"\",\""+modelID+"\",\""+level+"\"]")
		},
		OnModelThinkingLevelRemove: func(provider string, modelID string) {
			*events = append(*events, "onModelThinkingLevelRemove:[\""+provider+"\",\""+modelID+"\"]")
		},
		OnThemeChange:                  record("onThemeChange"),
		OnThemePreview:                 record("onThemePreview"),
		OnHideThinkingBlockChange:      recordBool("onHideThinkingBlockChange"),
		OnMermaidRenderingModeChange:   record("onMermaidRenderingModeChange"),
		OnShowCacheMissNoticesChange:   recordBool("onShowCacheMissNoticesChange"),
		OnCollapseChangelogChange:      recordBool("onCollapseChangelogChange"),
		OnEnableInstallTelemetryChange: recordBool("onEnableInstallTelemetryChange"),
		OnDoubleEscapeActionChange:     record("onDoubleEscapeActionChange"),
		OnTreeFilterModeChange:         record("onTreeFilterModeChange"),
		OnShowHardwareCursorChange:     recordBool("onShowHardwareCursorChange"),
		OnEditorPaddingXChange:         func(value int) { *events = append(*events, "onEditorPaddingXChange:"+itoa(value)) },
		OnOutputPadChange:              func(value int) { *events = append(*events, "onOutputPadChange:"+itoa(value)) },
		OnAutocompleteMaxVisibleChange: func(value int) { *events = append(*events, "onAutocompleteMaxVisibleChange:"+itoa(value)) },
		OnQuietStartupChange: func(value coding.QuietStartupSetting) {
			*events = append(*events, "onQuietStartupChange:"+coding.QuietStartupValueString(value))
		},
		OnDefaultProjectTrustChange:    record("onDefaultProjectTrustChange"),
		OnClearOnShrinkChange:          recordBool("onClearOnShrinkChange"),
		OnShowTerminalProgressChange:   recordBool("onShowTerminalProgressChange"),
		OnTuiModeChange:                record("onTuiModeChange"),
		OnFullscreenExitOutputChange:   record("onFullscreenExitOutputChange"),
		OnFullscreenScrollbarChange:    record("onFullscreenScrollbarChange"),
		OnFullscreenCopyOnSelectChange: recordBool("onFullscreenCopyOnSelectChange"),
		OnFullscreenWheelScrollLinesChange: func(lines tui.WheelScrollLines) {
			if lines.Auto {
				*events = append(*events, "onFullscreenWheelScrollLinesChange:auto")
				return
			}
			*events = append(*events, "onFullscreenWheelScrollLinesChange:"+itoa(lines.Lines))
		},
		OnWarningsChange: func(warnings WarningSettings) {
			encoded, _ := json.Marshal(warnings)
			*events = append(*events, "onWarningsChange:"+string(encoded))
		},
		OnCancel: func() { *events = append(*events, "onCancel:null") },
	}
}

// TestSettingsSelectorAgainstUpstreamGolden replays the settings selector
// renders and callback traces.
func TestSettingsSelectorAgainstUpstreamGolden(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	golden := loadGoldenFile(t, "testdata/settings_golden.txt")
	data, err := os.ReadFile("testdata/settings_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	corpus := settingsCorpus{}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}

	for _, label := range sortedKeys(corpus.Cases) {
		spec := corpus.Cases[label]
		config := baseSettingsConfig(t)
		applySettingsJSON(t, &config, spec.Config)
		events := []string{}
		component := NewSettingsSelectorComponent(config, recordingCallbacks(&events))
		list := component.GetSettingsList()
		for _, input := range spec.Inputs {
			list.HandleInput(input)
		}
		checkEasterGolden(t, golden, label+"@"+itoa(spec.Width), normalizeRender(component.Render(spec.Width)))
		if events == nil {
			events = []string{}
		}
		checkEasterGolden(t, golden, label+"-events", events)
	}
}

// TestTrustSettingDoesNotAdvertiseExtensions pins the trust row's description.
// It is upstream's text, and upstream lets an extension decide project trust;
// nothing in the port can (D41), so naming one describes a decider that never
// exists. The description is rendered under the selected row, so this drives the
// real component.
func TestTrustSettingDoesNotAdvertiseExtensions(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	events := []string{}
	component := NewSettingsSelectorComponent(baseSettingsConfig(t), recordingCallbacks(&events))
	component.GetSettingsList().SelectItem("default-project-trust")
	rendered := strings.Join(component.Render(120), "\n")
	if strings.Contains(rendered, "extension") {
		t.Fatalf("the trust row advertises extensions: %q", rendered)
	}
	if !strings.Contains(rendered, "Fallback behavior when no saved trust decision") {
		t.Fatalf("the trust row lost its description: %q", rendered)
	}
}

// TestSettingsSelectorHelpers covers the theme helpers.
func TestSettingsSelectorHelpers(t *testing.T) {
	themes := []string{"dark", "light", "solarized"}
	if got := preferredTheme(themes, "missing", true, "dark"); got != "dark" {
		t.Fatalf("preferredTheme fallback = %q", got)
	}
	if got := preferredTheme(themes, "light", true, "dark"); got != "light" {
		t.Fatalf("preferredTheme preferred = %q", got)
	}
	if got := preferredTheme(nil, "", false, "dark"); got != "dark" {
		t.Fatalf("preferredTheme empty = %q", got)
	}
	light, dark := defaultAutomaticThemes("solarized", themes)
	if light != "solarized" || dark != "solarized" {
		t.Fatalf("defaultAutomaticThemes = %q/%q", light, dark)
	}
	light, dark = defaultAutomaticThemes("light/dark", themes)
	if light != "light" || dark != "dark" {
		t.Fatalf("defaultAutomaticThemes auto = %q/%q", light, dark)
	}
	if summary := modelThinkingOverridesSummary(map[string]string{}); summary != "none" {
		t.Fatalf("summary = %q", summary)
	}
	if summary := modelThinkingOverridesSummary(map[string]string{"a/b": "high"}); summary != "1 configured" {
		t.Fatalf("summary = %q", summary)
	}
	items := themeItems(themes, "light")
	if items[1].Label != "✓ light" || items[0].Label != "  dark" {
		t.Fatalf("themeItems = %+v", items)
	}
	if items := singleModeThemeItems(themes, "dark"); items[0].Value != automaticThemeValue {
		t.Fatalf("singleModeThemeItems = %+v", items)
	}
	if _, ok := defaultProjectTrustByLabel("Always trust"); !ok {
		t.Fatal("trust label lookup failed")
	}
	if _, ok := defaultProjectTrustByLabel("nope"); ok {
		t.Fatal("unexpected trust label")
	}
}

// TestWheelScrollLinesCallbackCycle pins upstream's cycle values: a custom
// settings.json value (7) stays in the cycle, and three steps go 10, auto, 1
// (settings-selector.test.ts, f1927c2d5).
func TestWheelScrollLinesCallbackCycle(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	config := baseSettingsConfig(t)
	config.FullscreenWheelScrollLines = tui.FixedWheelScrollLines(7)
	events := []string{}
	component := NewSettingsSelectorComponent(config, recordingCallbacks(&events))
	list := component.GetSettingsList()
	list.SelectItem("fullscreen-wheel-scroll-lines")
	for i := 0; i < 3; i++ {
		list.HandleInput("\r")
	}
	want := []string{
		"onFullscreenWheelScrollLinesChange:10",
		"onFullscreenWheelScrollLinesChange:auto",
		"onFullscreenWheelScrollLinesChange:1",
	}
	if strings.Join(events, ",") != strings.Join(want, ",") {
		t.Fatalf("cycle = %v (want %v)", events, want)
	}
}

// TestThemeSubmenuGolden replays the theme submenu states.
func TestThemeSubmenuGolden(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	// The theme submenu is exercised through the main selector golden above;
	// verify the mode/state machine directly.
	callbacks := SettingsCallbacks{}
	var done []tui.SubmenuResult
	submenu := NewThemeSubmenu("dark", TerminalThemeDark, []string{"dark", "light"}, &callbacks,
		func(result tui.SubmenuResult) { done = append(done, result) })
	if submenu.Mode() != "single" {
		t.Fatalf("mode = %q", submenu.Mode())
	}
	// Choose Automatic (the list preselects the current theme, so move up
	// first): the mode switches and no completion fires.
	submenu.HandleInput("\x1b[A")
	submenu.HandleInput("\r")
	if submenu.Mode() != "automatic" {
		t.Fatalf("mode after enter = %q", submenu.Mode())
	}
	if len(done) != 0 {
		t.Fatalf("unexpected done calls: %+v", done)
	}
	// Change mode back to single (move down to the "Change mode" row).
	submenu.HandleInput("\x1b[B")
	submenu.HandleInput("\x1b[B")
	submenu.HandleInput("\x1b[B")
	submenu.HandleInput("\r")
	if submenu.Mode() != "single" {
		t.Fatalf("mode after change mode = %q", submenu.Mode())
	}
}

// TestWarningSettingsSubmenuToggles checks the warning toggle callbacks.
func TestWarningSettingsSubmenuToggles(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	var changes []WarningSettings
	submenu := newWarningSettingsSubmenu(WarningSettings{}, func(warnings WarningSettings) {
		changes = append(changes, warnings)
	}, func() {})
	// Enter cycles the value (true -> false -> true).
	submenu.HandleInput("\r")
	submenu.HandleInput("\r")
	if len(changes) != 2 {
		t.Fatalf("changes = %+v", changes)
	}
	first := changes[0]
	if first.AnthropicExtraUsage == nil || *first.AnthropicExtraUsage {
		t.Fatalf("first change = %+v", first)
	}
	last := changes[len(changes)-1]
	if last.AnthropicExtraUsage == nil || !*last.AnthropicExtraUsage {
		t.Fatalf("last change = %+v", last)
	}
	if !strings.Contains(strings.Join(submenu.Render(60), "\n"), "Anthropic extra usage") {
		t.Fatal("render missing label")
	}
}
