package interactive

import (
	"bufio"
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/dat267/pier/tui"
)

// The golden file is generated by running the upstream theme module with Node
// (tui/testdata/theme_golden.txt): every color token's ANSI sequence for the
// built-in dark/light themes in both color modes, the style helpers, the
// thinking/bash border colors, and the terminal-theme detection helpers.

func loadThemeGolden(t *testing.T) map[string]string {
	t.Helper()
	file, err := os.Open("testdata/theme_golden.txt")
	if err != nil {
		t.Fatalf("open golden: %v", err)
	}
	defer file.Close()
	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, " => ", 2)
		if len(parts) != 2 {
			t.Fatalf("bad golden line %q", line)
		}
		values[parts[0]] = parts[1]
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}
	return values
}

func themeGoldenCheck(t *testing.T, golden map[string]string, label string, got any) {
	t.Helper()
	want, ok := golden[label]
	if !ok {
		t.Fatalf("missing golden %q", label)
	}
	// Compare with sorted keys on both sides; the golden is JSON text and the
	// Go value is serialized to JSON first.
	gotStable := stableMDValue(mustParseJSON(t, mustJSON(got)))
	wantStable := stableMDValue(mustParseJSON(t, want))
	if gotStable != wantStable {
		t.Fatalf("%s:\n got %s\nwant %s", label, gotStable, wantStable)
	}
}

// TestThemeColorsAgainstUpstreamGolden verifies every color token's ANSI
// sequence and the style helpers.
func TestThemeColorsAgainstUpstreamGolden(t *testing.T) {
	golden := loadThemeGolden(t)

	for _, name := range []string{"dark", "light"} {
		themeJSON, ok := getBuiltinThemes()[name]
		if !ok {
			t.Fatalf("missing builtin theme %q", name)
		}
		resolved := ResolveThemeColors(themeJSON.Colors, themeJSON.Vars)
		for _, mode := range []ColorMode{ColorModeTruecolor, ColorMode256} {
			theme := CreateTheme(themeJSON, mode, "")
			keys := make([]string, 0, len(resolved))
			for key := range resolved {
				keys = append(keys, key)
			}
			sortStrings(keys)
			for _, color := range keys {
				if backgroundColorKeys[color] {
					label := "theme " + name + " " + string(mode) + " bg " + color
					want, ok := golden[label]
					if !ok {
						t.Fatalf("missing golden %q", label)
					}
					if got := mustJSON(theme.GetBgAnsi(color)); got != want {
						t.Fatalf("%s: got %s want %s", label, got, want)
					}
					continue
				}
				label := "theme " + name + " " + string(mode) + " fg " + color
				want, ok := golden[label]
				if !ok {
					t.Fatalf("missing golden %q", label)
				}
				if got := mustJSON(theme.GetFgAnsi(color)); got != want {
					t.Fatalf("%s: got %s want %s", label, got, want)
				}
			}
			applyLabel := "theme " + name + " " + string(mode) + " fg-apply"
			if want, ok := golden[applyLabel]; ok {
				got := theme.Fg("text", "x") + theme.Bg("selectedBg", "y")
				if mustJSON(got) != want {
					t.Fatalf("%s: got %s want %s", applyLabel, mustJSON(got), want)
				}
			}
		}
	}

	dark := CreateTheme(getBuiltinThemes()["dark"], ColorModeTruecolor, "")
	themeGoldenCheck(t, golden, "theme styles", []string{
		dark.Bold("x"), dark.Italic("x"), dark.Underline("x"), dark.Inverse("x"), dark.Strikethrough("x"),
	})
	var thinking []string
	for _, level := range []string{"off", "minimal", "low", "medium", "high", "xhigh", "max", "unknown"} {
		thinking = append(thinking, dark.GetThinkingBorderColor(level)("b"))
	}
	themeGoldenCheck(t, golden, "theme thinking", thinking)
	themeGoldenCheck(t, golden, "theme bash", dark.GetBashModeBorderColor()("b"))
	themeGoldenCheck(t, golden, "theme colorMode", []string{
		string(CreateTheme(getBuiltinThemes()["dark"], ColorModeTruecolor, "").ColorMode()),
		string(CreateTheme(getBuiltinThemes()["dark"], ColorMode256, "").ColorMode()),
	})
}

// TestThemeDetectionAgainstUpstreamGolden verifies the detection helpers.
func TestThemeDetectionAgainstUpstreamGolden(t *testing.T) {
	golden := loadThemeGolden(t)

	rgbResults := []any{}
	for _, rgb := range []RgbColor{{0, 0, 0}, {255, 255, 255}, {128, 128, 128}, {200, 200, 200}, {80, 80, 80}, {120, 120, 120}} {
		rgbResults = append(rgbResults, string(GetThemeForRgbColor(rgb)))
	}
	themeGoldenCheck(t, golden, "detect rgb", rgbResults)

	type detectionJSON struct {
		Theme      string `json:"theme"`
		Source     string `json:"source"`
		Detail     string `json:"detail"`
		Confidence string `json:"confidence"`
	}
	envCases := []map[string]string{
		{},
		{"COLORFGBG": "15;0"},
		{"COLORFGBG": "0;15"},
		{"COLORFGBG": "0;7"},
		{"COLORFGBG": "not;a;number"},
		{"COLORFGBG": "0;300"},
	}
	var detections []detectionJSON
	for _, env := range envCases {
		detection := DetectTerminalBackgroundFromEnv(func(key string) string { return env[key] })
		detections = append(detections, detectionJSON{
			Theme:      string(detection.Theme),
			Source:     detection.Source,
			Detail:     detection.Detail,
			Confidence: detection.Confidence,
		})
	}
	themeGoldenCheck(t, golden, "detect env", detections)

	autoResults := []any{}
	for _, setting := range []*string{nil, strPtr("light/dark"), strPtr("light/dark/extra"), strPtr("/dark"), strPtr("light/"), strPtr(" light / dark "), strPtr("plain")} {
		light, dark, ok := ParseAutoThemeSetting(setting)
		if !ok {
			autoResults = append(autoResults, nil)
			continue
		}
		autoResults = append(autoResults, map[string]string{"lightTheme": light, "darkTheme": dark})
	}
	themeGoldenCheck(t, golden, "auto setting", autoResults)

	resolveResults := []any{}
	for _, testCase := range []struct {
		setting *string
		theme   TerminalTheme
	}{
		{nil, TerminalThemeDark},
		{strPtr("light/dark"), TerminalThemeLight},
		{strPtr("light/dark"), TerminalThemeDark},
		{strPtr("solarized"), TerminalThemeDark},
		{strPtr("bad/"), TerminalThemeDark},
		{strPtr("a/b/c"), TerminalThemeDark},
	} {
		resolved, ok := ResolveThemeSetting(testCase.setting, testCase.theme)
		if !ok {
			resolveResults = append(resolveResults, nil)
			continue
		}
		resolveResults = append(resolveResults, resolved)
	}
	themeGoldenCheck(t, golden, "resolve setting", resolveResults)

	themeGoldenCheck(t, golden, "available", AvailableThemes())
}

func strPtr(value string) *string { return &value }

// TestThemeValidation covers the structural theme validation.
func TestThemeValidation(t *testing.T) {
	data, err := os.ReadFile("themes/dark.json")
	if err != nil {
		t.Fatalf("read dark theme: %v", err)
	}
	if _, err := ValidateThemeJSON("dark", data); err != nil {
		t.Fatalf("dark theme invalid: %v", err)
	}

	// A theme missing required colors reports them sorted.
	missing := []byte(`{"name":"broken","colors":{"accent":"#fff"}}`)
	_, err = ValidateThemeJSON("broken", missing)
	if err == nil {
		t.Fatal("expected validation error")
	}
	message := err.Error()
	if !strings.Contains(message, "Missing required color tokens:") || !strings.Contains(message, "  - bashMode") {
		t.Fatalf("unexpected message: %s", message)
	}
	if !(strings.Index(message, "  - bashMode") < strings.Index(message, "  - border")) {
		t.Fatalf("missing colors not sorted: %s", message)
	}

	// Names with a slash are rejected once the colors are complete.
	complete := map[string]any{}
	for _, key := range requiredThemeColors {
		complete[key] = "#000000"
	}
	withSlash, err := json.Marshal(map[string]any{"name": "a/b", "colors": complete})
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	_, err = ValidateThemeJSON("x", withSlash)
	if err == nil || !strings.Contains(err.Error(), "reserved for automatic light/dark") {
		t.Fatalf("slash name error = %v", err)
	}

	// The relaxed parse accepts built-in style documents without a name check.
	if _, err := ParseThemeJSON("relaxed", data, false); err != nil {
		t.Fatalf("relaxed parse: %v", err)
	}
}

// TestThemeFallbacksAndVarResolution covers the color fallbacks and variable
// resolution.
func TestThemeFallbacksAndVarResolution(t *testing.T) {
	colors := map[string]ColorValue{
		"muted":         {Value: "#111111"},
		"text":          {Value: "#222222"},
		"thinkingXhigh": {Value: "#333333"},
		"selectedBg":    {Value: "#444444"},
	}
	vars := map[string]ColorValue{"primary": {Value: "#aabbcc"}, "alias": {Value: "primary"}}
	resolved := ResolveThemeColors(map[string]ColorValue{
		"accent": {Value: "alias"},
		"border": {Value: "#000000"},
		"index":  {Index: 42, IsIndex: true},
		"empty":  {Value: ""},
	}, vars)
	if resolved["accent"].Value != "#aabbcc" {
		t.Fatalf("accent = %+v", resolved["accent"])
	}
	if !resolved["index"].IsIndex || resolved["index"].Index != 42 {
		t.Fatalf("index = %+v", resolved["index"])
	}

	theme := NewTheme(colors, map[string]ColorValue{"selectedBg": colors["selectedBg"]}, ColorModeTruecolor, "t", "")
	if got := theme.GetFgAnsi("scrollbarTrack"); got != "\x1b[38;2;17;17;17m" {
		t.Fatalf("scrollbarTrack fallback = %q", got)
	}
	if got := theme.GetFgAnsi("searchMatchText"); got != "\x1b[38;2;34;34;34m" {
		t.Fatalf("searchMatchText fallback = %q", got)
	}
	if got := theme.GetBgAnsi("searchMatchBg"); got != "\x1b[48;2;68;68;68m" {
		t.Fatalf("searchMatchBg fallback = %q", got)
	}

	// Circular and missing references panic like upstream's throws.
	assertPanics(t, "circular", func() {
		ResolveThemeColors(map[string]ColorValue{"a": {Value: "b"}}, map[string]ColorValue{"b": {Value: "a"}})
	})
	assertPanics(t, "missing", func() {
		ResolveThemeColors(map[string]ColorValue{"a": {Value: "nope"}}, nil)
	})
}

// TestThemeRegistry covers the global theme lifecycle.
func TestThemeRegistry(t *testing.T) {
	dir := t.TempDir()
	SetCustomThemesDir(dir)

	if _, _, ok := ParseAutoThemeSetting(nil); ok {
		t.Fatal("nil setting must not parse")
	}

	InitTheme("light", false)
	if CurrentThemeName() != "light" {
		t.Fatalf("name = %q", CurrentThemeName())
	}
	if CurrentTheme() == nil || CurrentTheme().Name != "light" {
		t.Fatalf("theme = %+v", CurrentTheme())
	}

	changed := 0
	OnThemeChange(func() { changed++ })
	success, message := SetTheme("dark", false)
	if !success || message != "" || CurrentTheme().Name != "dark" {
		t.Fatalf("set theme = %v %q", success, message)
	}
	if changed != 1 {
		t.Fatalf("change callback = %d", changed)
	}
	success, message = SetTheme("does-not-exist", false)
	if success || !strings.Contains(message, "Theme not found") {
		t.Fatalf("missing theme = %v %q", success, message)
	}
	if CurrentThemeName() != "dark" {
		t.Fatalf("fallback name = %q", CurrentThemeName())
	}

	// Registered themes take precedence and are listed.
	custom := CreateTheme(getBuiltinThemes()["dark"], ColorModeTruecolor, "")
	custom.Name = "custom-theme"
	SetRegisteredThemes([]*Theme{custom})
	if got := GetThemeByName("custom-theme"); got == nil || got.Name != "custom-theme" {
		t.Fatalf("registered lookup = %+v", got)
	}
	names := AvailableThemes()
	if !containsString(names, "custom-theme") || !containsString(names, "dark") {
		t.Fatalf("available = %v", names)
	}
	SetRegisteredThemes(nil)
	if GetThemeByName("custom-theme") != nil {
		t.Fatal("registered themes not cleared")
	}

	// Custom theme files are discovered and loaded.
	writeThemeFile(t, dir, "mytheme.json", "mytheme", "#ff0000")
	SetRegisteredThemes(nil)
	loaded, err := LoadThemeFromPath(dir+"/mytheme.json", ColorMode256)
	if err != nil {
		t.Fatalf("load custom: %v", err)
	}
	if loaded.Name != "mytheme" || loaded.ColorMode() != ColorMode256 {
		t.Fatalf("custom theme = %+v", loaded)
	}
	if !containsString(AvailableThemes(), "mytheme") {
		t.Fatalf("custom theme not listed: %v", AvailableThemes())
	}

	instance := CreateTheme(getBuiltinThemes()["light"], ColorModeTruecolor, "")
	SetThemeInstance(instance)
	if CurrentThemeName() != "<in-memory>" || CurrentTheme() != instance {
		t.Fatalf("instance = %q %+v", CurrentThemeName(), CurrentTheme())
	}
	StopThemeWatcher()
}

func writeThemeFile(t *testing.T, dir string, file string, name string, accent string) {
	t.Helper()
	colors := map[string]any{}
	for _, key := range requiredThemeColors {
		colors[key] = accent
	}
	document := map[string]any{"name": name, "colors": colors}
	data, err := json.Marshal(document)
	if err != nil {
		t.Fatalf("marshal theme: %v", err)
	}
	if err := os.WriteFile(dir+"/"+file, data, 0o644); err != nil {
		t.Fatalf("write theme: %v", err)
	}
}

// TestAnsi256PaletteToHex verifies palette-index conversion and rejects malformed hex.
func TestAnsi256PaletteToHex(t *testing.T) {
	if _, err := hexToRgb("#12345"); err == nil {
		t.Fatal("short hex accepted")
	}
	if _, err := hexToRgb("#zzzzzz"); err == nil {
		t.Fatal("non-hex accepted")
	}
	// The 256-color palette round-trips through ansi256ToHex.
	if got := ansi256ToHex(196); got != "#ff0000" {
		t.Fatalf("ansi256ToHex(196) = %s", got)
	}
	if got := ansi256ToHex(232); got != "#080808" {
		t.Fatalf("ansi256ToHex(232) = %s", got)
	}
	if got := ansi256ToHex(15); got != "#ffffff" {
		t.Fatalf("ansi256ToHex(15) = %s", got)
	}
}

// TestBuiltinThemeDocuments verifies the embedded theme documents load.
func TestBuiltinThemeDocuments(t *testing.T) {
	for _, name := range []string{"dark", "light"} {
		theme := CreateTheme(getBuiltinThemes()[name], ColorModeTruecolor, "")
		if theme == nil || theme.Name != name {
			t.Fatalf("theme %s = %+v", name, theme)
		}
		if _, ok := theme.fgColors["text"]; !ok {
			t.Fatalf("theme %s missing text color", name)
		}
		if _, ok := theme.bgColors["selectedBg"]; !ok {
			t.Fatalf("theme %s missing selectedBg", name)
		}
	}
}

// TestThemeHandleResolvesTheCurrentTheme pins the Proxy-equivalent handle:
// ActiveTheme returns a stable pointer whose Fg/Bg resolve the current concrete
// theme, so holders recolor on a switch without a rebuild.
func TestThemeHandleResolvesTheCurrentTheme(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	InitTheme("dark", false)

	handle := ActiveTheme()
	if got, want := handle.Fg("accent", "x"), mustLoadTheme("dark").Fg("accent", "x"); got != want {
		t.Fatalf("dark handle = %q want %q", got, want)
	}

	SetTheme("light", false)
	if ActiveTheme() != handle {
		t.Fatal("ActiveTheme returned a new pointer; captured holders would go stale")
	}
	if got, want := handle.Fg("accent", "x"), mustLoadTheme("light").Fg("accent", "x"); got != want {
		t.Fatalf("light handle = %q want %q", got, want)
	}
	if handle.ColorMode() != mustLoadTheme("light").ColorMode() {
		t.Fatal("ColorMode did not resolve the new theme")
	}
}

// TestMarkdownThemeRecolorsAfterASwitch pins that a factory built once from the
// handle recolors on invalidate after a theme switch.
func TestMarkdownThemeRecolorsAfterASwitch(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	InitTheme("dark", false)

	markdown := tui.NewMarkdown("# heading\n\nbody text", 0, 0, GetMarkdownTheme(), nil, tui.MarkdownOptions{})
	dark := strings.Join(markdown.Render(40), "\n")

	SetTheme("light", false)
	markdown.Invalidate()
	light := strings.Join(markdown.Render(40), "\n")

	if dark == light {
		t.Fatalf("markdown did not recolor:\n%s", dark)
	}
}

// TestThemeColorsAcceptOklchAndOkhsl pins that theme JSON color values in OKLCH
// or OKHSL survive variable resolution and parse into concrete colors
// (upstream parseColor).
func TestThemeColorsAcceptOklchAndOkhsl(t *testing.T) {
	values := map[string]string{
		"oklch":  "oklch(62% 0.1 200)",
		"oklch2": "oklch(0.627955 0.257683 29.2339)",
		"okhsl":  "OKHSL(250deg 60% 55%)",
		"okhsl2": "okhsl(29.23 100% 56.8%)",
	}
	colors := map[string]ColorValue{}
	for key, value := range values {
		colors[key] = ColorValue{Value: value}
	}
	resolved := ResolveThemeColors(colors, nil)
	theme := NewTheme(resolved, map[string]ColorValue{}, ColorModeTruecolor, "test", "")
	for key, value := range values {
		want, err := tui.ParseColor(value)
		if err != nil {
			t.Fatalf("ParseColor(%q): %v", value, err)
		}
		if got := theme.Colors()[key]; got != want {
			t.Fatalf("%s = %+v (want %+v)", value, got, want)
		}
	}
}
