package interactive

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/dat267/pier/tui"
)

// The golden file is generated by running the exact style expressions from
// upstream tui-renderer.ts with Node
// (coding/interactive/testdata/tuirenderer_golden.txt).

// TestInteractiveTuiStyleExpressionsAgainstUpstreamGolden replays the
// fullscreen option closures' style expressions.
func TestInteractiveTuiStyleExpressionsAgainstUpstreamGolden(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	data, err := os.ReadFile("testdata/tuirenderer_corpus.json")
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	var corpus struct {
		Text string `json:"text"`
	}
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}
	golden := loadGoldenFile(t, "testdata/tuirenderer_golden.txt")
	theme := ActiveTheme()

	styleSearchMatch := func(text string) string {
		return theme.Bg("searchMatchBg", theme.Fg("searchMatchText", text))
	}
	checkEasterGolden(t, golden, "searchMatchStyle", theme.Underline(styleSearchMatch(corpus.Text)))
	checkEasterGolden(t, golden, "searchCurrentMatchStyle",
		theme.Bold(theme.Inverse(styleSearchMatch(corpus.Text))))
	checkEasterGolden(t, golden, "searchNavigationButtonStyle",
		[]string{theme.Underline(corpus.Text), corpus.Text})

	shortcut := KeyDisplayText("tui.altScreen.bottom")
	label := " ↓ Jump to latest message"
	if shortcut != "" {
		label += " · " + shortcut
	}
	label += " "
	checkEasterGolden(t, golden, "scrollToEndIndicator", theme.Bg("selectedBg", theme.Fg("text", label)))
	checkEasterGolden(t, golden, "shortcut", shortcut)
}

// TestCreateInteractiveTuiModes checks the renderer selection.
func TestCreateInteractiveTuiModes(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	terminal := &fakeRendererTerminal{width: 80, height: 24}

	regular := CreateInteractiveTui(InteractiveTuiOptions{
		TuiMode: "regular", ShowHardwareCursor: true, LogDirectory: "/tmp/logs", Terminal: terminal,
	})
	mainScreen, ok := regular.(*tui.MainScreen)
	if !ok {
		t.Fatalf("regular renderer = %T", regular)
	}
	if !mainScreen.GetShowHardwareCursor() {
		t.Fatal("hardware cursor not propagated")
	}
	if mainScreen.GetTerminal() != tui.Terminal(terminal) {
		t.Fatal("terminal not propagated")
	}

	fullscreen := CreateInteractiveTui(InteractiveTuiOptions{
		TuiMode: "fullscreen", ShowHardwareCursor: false, LogDirectory: "/tmp/logs", Terminal: terminal,
	})
	altScreen, ok := fullscreen.(*tui.AltScreen)
	if !ok {
		t.Fatalf("fullscreen renderer = %T", fullscreen)
	}
	if altScreen.GetShowHardwareCursor() {
		t.Fatal("hardware cursor should be off")
	}
	// The alt screen exposes the layout-root seam used by the viewport TUI.
	altScreen.SetLayoutRoot(&staticRendererComponent{lines: []string{"hello"}})
	if altScreen.LayoutRoot() == nil {
		t.Fatal("layout root not set")
	}

	// The default terminal path must not panic.
	_ = CreateInteractiveTui(InteractiveTuiOptions{TuiMode: "regular"})
}

// TestInteractiveTuiReferenceForwarding checks that the reference follows the
// active renderer across swaps.
func TestInteractiveTuiReferenceForwarding(t *testing.T) {
	SetCustomThemesDir(t.TempDir())
	SetRegisteredThemes(nil)
	SetTrueColorSupport(true)
	SetStyleColorsEnabled(true)
	InitTheme("dark", false)

	terminal := &fakeRendererTerminal{width: 40, height: 12}
	first := CreateInteractiveTui(InteractiveTuiOptions{TuiMode: "regular", Terminal: terminal})
	second := CreateInteractiveTui(InteractiveTuiOptions{TuiMode: "fullscreen", Terminal: terminal})

	active := first
	reference := CreateInteractiveTuiReference(func() tui.TUI { return active })

	child := &staticRendererComponent{lines: []string{"child"}}
	reference.AddChild(child)
	if len(first.GetMountedRoots()) != 1 {
		t.Fatalf("first roots = %d", len(first.GetMountedRoots()))
	}

	// Swap: the reference now targets the alt screen.
	active = second
	reference.AddChild(&staticRendererComponent{lines: []string{"second"}})
	if len(first.GetMountedRoots()) != 1 {
		t.Fatalf("first roots after swap = %d", len(first.GetMountedRoots()))
	}
	if len(second.GetMountedRoots()) != 1 {
		t.Fatalf("second roots = %d", len(second.GetMountedRoots()))
	}
	if reference.GetTerminal() != tui.Terminal(terminal) {
		t.Fatal("terminal mismatch")
	}
	if got := reference.Render(40); len(got) == 0 {
		t.Fatal("empty render")
	}
	reference.RequestRender(true)
	reference.SetFocus(child)
	reference.Clear()
	if len(second.GetMountedRoots()) != 0 {
		t.Fatalf("second roots after clear = %d", len(second.GetMountedRoots()))
	}
	reference.RemoveChild(child)
	if reference.HasOverlay() {
		t.Fatal("unexpected overlay")
	}
}

// fakeRendererTerminal is an in-memory terminal for the renderer tests.
type fakeRendererTerminal struct {
	programStatuses []tui.ProgramStatus
	width           int
	height          int
}

func (f *fakeRendererTerminal) Start(onInput func(string), onResize func()) {}
func (f *fakeRendererTerminal) Stop()                                       {}
func (f *fakeRendererTerminal) DrainInput(maxMs int, idleMs int) error      { return nil }
func (f *fakeRendererTerminal) Write(data string)                           {}
func (f *fakeRendererTerminal) Columns() int                                { return f.width }
func (f *fakeRendererTerminal) Rows() int                                   { return f.height }
func (f *fakeRendererTerminal) KittyProtocolActive() bool                   { return false }
func (f *fakeRendererTerminal) MoveBy(lines int)                            {}
func (f *fakeRendererTerminal) HideCursor()                                 {}
func (f *fakeRendererTerminal) ShowCursor()                                 {}
func (f *fakeRendererTerminal) ClearLine()                                  {}
func (f *fakeRendererTerminal) ClearFromCursor()                            {}
func (f *fakeRendererTerminal) ClearScreen()                                {}
func (f *fakeRendererTerminal) SetTitle(title string)                       {}
func (f *fakeRendererTerminal) SetProgress(active bool)                     {}

// SetProgramStatus records the reports the interactive mode would have sent (OSC 7501).
func (f *fakeRendererTerminal) SetProgramStatus(status tui.ProgramStatus) {
	f.programStatuses = append(f.programStatuses, status)
}

// staticRendererComponent renders fixed lines.
type staticRendererComponent struct {
	lines []string
}

func (s *staticRendererComponent) Render(width int) []string { return s.lines }
func (s *staticRendererComponent) Invalidate()               {}
