package interactive

import (
	"os"
	"path/filepath"
	"testing"
	"time"
)

// TestMain pins the process timezone. The upstream-derived goldens were
// generated by driving the TypeScript with Node at UTC+7 (tree-selector label
// timestamps render in local time, e.g. "20/3/4 12:06"); CI runs in UTC and
// would otherwise see "05:06". The fixed zone needs no tzdata.
//
// It also pins the editor environment. EditInExternalEditor hands this process's
// console and environment to whatever VISUAL/EDITOR resolves to, so a test that
// reached the real runner would launch the developer's editor mid-run — and on
// Windows, where the spawn goes through `cmd /c`, a command that cannot be
// executed makes the shell open the temp prompt file with its association
// instead (running the suite opened VS Code on temp paths that way). Tests that
// exercise the editor stub the runner (stubExternalEditorRunner); this pin makes
// an accident fail instead of opening something on the developer's desktop.
func TestMain(m *testing.M) {
	time.Local = time.FixedZone("golden", 7*60*60)
	noEditor := filepath.Join(os.TempDir(), "pier-test-no-external-editor")
	os.Setenv("VISUAL", noEditor)
	os.Setenv("EDITOR", noEditor)
	// No test may write into the developer's real agent directory: a session
	// manager built with the default agent dir created a session shard per temp
	// cwd there. Pin it for the whole binary.
	dir, err := os.MkdirTemp("", "pier-test-agent-")
	if err == nil {
		os.Setenv("PI_CODING_AGENT_DIR", dir)
	}
	code := m.Run()
	if err == nil {
		_ = os.RemoveAll(dir)
	}
	os.Exit(code)
}
